### ISSUE TITLE
[3.3] Missing defined('MOODLE_INTERNAL') || die(); 

### ISSUE THREAD

**Issue by CholitoBest** [gjb2048/moodle-format_grid#100]
It looks like defined('MOODLE_INTERNAL') || die(); is missing in following files (reg. Moodle 3.3 version):

* js/gf_colourpopup.php
* tests/courseformatlib_test.php
* upgrade/convert_legacy_image.php

Best regards,
Olena Tatarintseva

**Comment by gjb2048** [comment]
Dear Olena,

No they are not!  -> https://github.com/gjb2048/moodle-format_grid/blob/V3.3.0.6/js/gf_colourpopup.php#L28 - please update and check you have the current version before reporting issues: https://moodle.org/plugins/pluginversion.php?id=19696.

G
