### ISSUE TITLE
Embedly code only appears in editing mode in grid format

### ISSUE THREAD

**Issue by Connor-Overt** [gjb2048/moodle-format_grid#102]
We have come across a rather strange issue. 

We tried to embed this code below into a Moodle topic in grid format but upon exiting editing mode the code doesn't work: 
`
#<blockquote class="embedly-card">
#<h4><a href="https://www.nhs.uk/live-well/exercise/">Exercise</a></h4>
#<p>To stay healthy or improve health, adults need to do 2 types of physical activity each #week: aerobic and strength exercises. How much physical activity you need to do each week #depends on your age.</p>
#</blockquote>
#<script src="https://cdn.embedly.com/widgets/platform.js" type="text/javascript"></script> 
`

I've added the '#'s to the code above so it shows correctly in here, they should be removed when testing. 

Is there any reason that embedly code such as the above wouldn't sit well with the grid format code?

Thanks! 

Connor

**Comment by gjb2048** [comment]
Dear Connor,

Nothing to do with the Grid format, rather that Moodle strips out iffy markup as a part of the editor filter process.  This will happen with any course format.

G
