### ISSUE TITLE
After upgrade to moodle 3.7: empty

### ISSUE THREAD

**Issue by behoof** [gjb2048/moodle-format_grid#103]
Upgraded to moodle 3.7.

All resources and activities are not shown for student and teacher. Section zero (on top of the icons) is not shown

Debug shows:
Error: mdb->get_record() found more than one record!
line 1599 of /lib/dml/moodle_database.php: call to debugging()
line 1559 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1538 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 2020 of /course/format/grid/lib.php: call to moodle_database->get_record()
line 86 of /course/format/grid/lib.php: call to format_grid->get_summary_visibility()
line 53 of /course/format/grid/renderer.php: call to format_grid->is_section0_attop()
line 417 of /lib/outputfactories.php: call to format_grid_renderer->__construct()
line 2454 of /lib/outputlib.php: call to theme_overridden_renderer_factory->get_renderer()
line 864 of /lib/pagelib.php: call to theme_config->get_renderer()
line 141 of /course/view.php: call to moodle_page->get_renderer()

When switching Course Layout to "show all sections on one page":  the content is visible (popup window) for the student, but not for the teacher.

When switching to other course formats: 
- Onetopic: empty
- Buttons: content visible.
- Topics Format: empty
- Weekly Format: empty
-Tile Format: content visible when expand

When creating a new course: same issue

Best regards

Bert

**Comment by gjb2048** [comment]
Hi Bert,

Ok...

Given the stack trace then that is to the summary record and would not have caused the modules not to show.  Some questions:

1. What exact version of Moodle and the Grid format.
2. What exact version of Moodle and the Grid format did you upgrade from.
3. What upgrade procedure did you follow.
4. Did the problem happen when you tested the upgrade procedure on your test server.
5. Was there any corruption or issues that happened during the upgrade.
6. Does the problem still happen if you restore the course from your backup of it?

G

**Comment by gjb2048** [comment]
Note: Stack trace related to #97

**Comment by behoof** [comment]
Hi G,

Thanks for your quick response. 

Moodle 3.7.2 | Grid 3.7.0.2 - 2019052501 
Was upgrading from 3.5.. But installing on Moodle 3.7.1 didn't give the problem. Installing on an blanc testserver showed that the problem happens when other course formats (buttons,   edwiser course formats, social) where installed.  So the problem was gone when I uninstalled other course formats. Apparently one of them did the wrong trick. All working fine now with Grid and Ontetopic course format. 

Though debugging gives me the messages below.

Best regards,

Bert



line 53 of /course/format/grid/renderer.php: call to format_grid->is_section0_attop()
line 417 of /lib/outputfactories.php: call to format_grid_renderer->__construct()
line 2454 of /lib/outputlib.php: call to theme_overridden_renderer_factory->get_renderer()
line 864 of /lib/pagelib.php: call to theme_config->get_renderer()
line 141 of /course/view.php: call to moodle_page->get_renderer()

Warning: max(): Array must contain at least one element in /home/cgiadmin/domains/cgi-training.nl/public_html/course/format/lib.php on line 287

Warning: max(): Array must contain at least one element in /home/cgiadmin/domains/cgi-training.nl/public_html/course/format/lib.php on line 287

Warning: max(): Array must contain at least one element in /home/cgiadmin/domains/cgi-training.nl/public_html/course/format/lib.php on line 287

**Comment by behoof** [comment]
It was the Buttons course format disturbing all course formats. Programmer informed.

**Comment by gjb2048** [comment]
Thanks for letting me know Bert.

The second stack trace seems to make no sense.

The warnings are related to the issues caused by the Buttons format.
