### ISSUE TITLE
Fix section one not shown

### ISSUE THREAD

**Issue by mpotier** [gjb2048/moodle-format_grid#105]
Hi!
We have just switched to V3.7 + https
The courses that have only one section displayed (the others are hidden) have a faulty link. 

- If it is the first section that is displayed only,  the link works.
- If this is one of the following, the link on the section is no longer operational.

Example with 4 sections :
- first section displayed and 2, 3, 4 hidden - It's OK
- if 1the first hidden and only one section displayed  (2 or 3 or 4) = non-operational link.

**Comment by gjb2048** [comment]
What is the value of the course layout setting?

Can you supply an example MBZ file with no user data that demonstrates this?

**Comment by gjb2048** [comment]
Ok, can replicate.

**Comment by gjb2048** [comment]
Ok, https://github.com/gjb2048/moodle-format_grid/commit/68a65e531e5de77081dfed0d92215f051e128647 should fix it, please could you test and confirm.

**Comment by mpotier** [comment]
Everything looks super.
Thank you for the fast work.

  ----- Message de Gareth J Barnard <notifications@github.com> ---------
      Date: Fri, 08 Nov 2019 14:09:55 -0800
        De: Gareth J Barnard <notifications@github.com>
Répondre à: gjb2048/moodle-format_grid  
<reply@reply.github.com>
     Objet: Re: [gjb2048/moodle-format_grid] Fix section one not shown (#105)
         À: gjb2048/moodle-format_grid <moodle-format_grid@noreply.github.com>
        Cc: mpotier <mylene.potier@iutenligne.net>, Author  
<author@noreply.github.com>

> Ok, 68a65e5[1] should fix it, please could you test and confirm.
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[2], or unsubscribe[3].

----- Fin du message de Gareth J Barnard <notifications@github.com> -----



Liens:
------
[1]  
https://github.com/gjb2048/moodle-format_grid/commit/68a65e531e5de77081dfed0d92215f051e128647
[2]  
https://github.com/gjb2048/moodle-format_grid/issues/105?email_source=notifications&email_token=AGHFYES6HD5GWWMI6XFHFX3QSXPTHA5CNFSM4JKVGBGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDTP2GI#issuecomment-552008985
[3]
