### ISSUE TITLE
Same color setting for "set or change img" as currentselectedimagecontainertextcolor in editing on

### ISSUE THREAD

**Issue by tholudwig** [gjb2048/moodle-format_grid#106]
The text color and the color of the container for an element can be set individually for each course. Unfortunately, depending on the settings, it can happen that "set or change im" can no longer be read in editing on.
It would therefore be nicer if the text color were the same as for currenctselectedimagecontainertextcolor. Unfortunately the cog is included as img and not as font awesome. Then this element would also be displayed according to the set color.
![set or change img](https://user-images.githubusercontent.com/14368866/74339630-c26b2b00-4da4-11ea-973e-f15ccb75db19.png)
![set or change img 2](https://user-images.githubusercontent.com/14368866/74339635-c39c5800-4da4-11ea-91ea-5e984014b896.png)

**Comment by gjb2048** [comment]
Ok, technically a bug.

**Comment by gjb2048** [comment]
Ok, as the current selected functionality is not required when editing as the grid key functionality is disabled, then the solution is not to have a current selected.  Thus no longer a colour issue to fix.

**Comment by gjb2048** [comment]
Also made the icon a 'pix_icon' so that the core icon system will make it a FontAwesome one if such is implemented in a theme.
