### ISSUE TITLE
Moodle 3.9 version bug

### ISSUE THREAD

**Issue by Urpokarhu1** [gjb2048/moodle-format_grid#118]
Hello,

I tested format_grid 3.8.0.1 (2019111700) with Moodle 3.9beta (Build: 20200607). 

I know Moodle 3.9 haven't been released yet but maybe this will help you in 3.9 development of this plugin.

When you move a section to a different location on a course it stays in infinite loading cycle and never stops.

![infnite loading](https://user-images.githubusercontent.com/53904029/84241080-a20b6d00-ab07-11ea-8323-476705435be5.PNG)

**Comment by gjb2048** [comment]
Thanks for the heads up, what would really help is a fix please.

**Comment by gjb2048** [comment]
Is MDL-68231 and MDL-65539 - done as a part of the upgrade process.
