### ISSUE TITLE
Bug in default/global settings

### ISSUE THREAD

**Issue by mmpetri** [gjb2048/moodle-format_grid#119]
Bug in setting default settings

When changing Course display default (format_grid | defaultcoursedisplay) in global settings to -> 'Show one section per page', that setting does not become the default setting when creating new course, nor there is option to reset older grid-courses to that setting.

Moodle 3.5.12 (Build: 20200511)
plugin->version = 2018052306
and
Moodle 3.8.3+ (Build: 20200609)
plugin->version = 2019111700;

**Comment by gjb2048** [comment]
Interesting, looks like 'defaultcoursedisplay' is redundant as the core default is being used.  So needs to be removed.

Also 'nor there is option to reset older grid-courses to that setting' would be an 'improvement' and not a 'bug' so would need funding please.
