### ISSUE TITLE
Editing is turned off automatically after adding a resource

### ISSUE THREAD

**Issue by sieste** [gjb2048/moodle-format_grid#123]
Problem:

- click on "Turn editing on" 
- add a resource (e.g. a URL) to a tile
- Click "Save and exit"
- Editing is now turned off

Expected behavior:

- Editing remains turned on so I can add more resources

**Comment by gjb2048** [comment]
Moodle / theme versions please.

**Comment by gjb2048** [comment]
Cannot reproduce in Moodle 3.9.1+ (Build: 20200903) with Grid 3.9.0.2 - please supply more evidence, screen shots, screencast etc.

**Comment by sieste** [comment]
Found the solution: Edit settings (blue cog) -> Course format -> Course layout -> Show one section per page.

**Comment by gjb2048** [comment]
??? So how does this solve the issue when the testing instructions imply that when saving and exiting that editing is turned off?
