### ISSUE TITLE
Soft link not working

### ISSUE THREAD

**Issue by behoof** [gjb2048/moodle-format_grid#125]
When I use a section title in section 0, I see the the link of that section as usual. But clicking on it doesn't bring me to the section. Copying the link gives: M.format_grid.tab(3)

**Comment by gjb2048** [comment]
@behoof What version of the format / Moodle please?  Please supply steps to replicate and a screen shot.

**Comment by gjb2048** [comment]
@behoof Please reply or I'll close the issue.  I cannot currently replicate.

**Comment by gjb2048** [comment]
@behoof No reply, closing.
