### ISSUE TITLE
Grid images not loading in IE11

### ISSUE THREAD

**Issue by jamestombs** [gjb2048/moodle-format_grid#127]
We've come across a situation where JPEG grid images don't load in IE11 and in the console produce the following error:

`DOM7009: Unable to decode image at URL`

After some investigation it appears that in newer versions of Apache the following Content-Type-Option header is set by default.

`Header set X-Content-Type-Options: "nosniff"`

Commenting this out (as it was in previous versions of Apache) fixes this and the images display.

This bug only appears for JPEG files uploaded to Grid. PNG files uploaded to Grid work fine and JPEG files uploaded through other plugins work fine.

**Comment by gjb2048** [comment]
But Grid uses Moodle to serve the image with moodle_url::make_pluginfile_url(), therefore not a Grid issue but a core one.

**Comment by jamestombs** [comment]
@gjb2048 That's dismissing the fact that Grid module resizes the uploaded image and is obviously doing something wrong as IE can't decode.

I uploaded a JPEG image with the following properties (using linux file)

`/home/v2/6ty4uhzr42161.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1920x1920, frames 3`

The converted image from \format_grid->create_section_image() produces a file prepended with 3_goi_ which results in the following:

`/home/v2/3_goi_6ty4uhzr42161.jpg: PNG image data, 210 x 140, 8-bit/color RGBA, non-interlaced`

So I'd say this is very much a Grid issue, not a core issue.

**Comment by gjb2048** [comment]
Ok, tested and currently, cannot replicate.  What version of Moodle / Grid format are you using please?

**Comment by jamestombs** [comment]
Grid is version 2017071704 (2.9.1.8) which is the latest version we've got to work with 3.3.9 (Build: 20181112) (which is actually Totara 12.18 (Build: 20200521.00).

I think the issue is that the resizing of the image for the thumbnail in lib/gdlib.php, function resize_image_from_image(), it checks for imagepng first and if that exists uses that rather than maintaining the mimetype of the uploaded file.

Chrome and Firefox don't care that it's a .jpg extension and will read the mimetype from the file and display without issue. However IE11 is very strict and won't display an image if the mimetype differs from the file extension.

It doesn't look like resize_image_from_image() has been changed from our version to the latest, and the function in Grid only has one extra line which is about background colour.

In my example above the response headers are:

````
HTTP/1.1 200 OK
Date: Wed, 25 Nov 2020 11:05:12 GMT
Server: Apache/2.4.46
Content-Disposition: inline; filename*=utf-8''3_goi_6ty4uhzr42161.jpg
Cache-Control: private, max-age=3600, no-transform
Expires: Wed, 25 Nov 2020 12:05:12 GMT
Pragma: 
Accept-Ranges: bytes
Etag: "44d91967f697331848d56d720a164b2a5b2a4a8f"
Last-Modified: Wed, 25 Nov 2020 10:23:34 GMT
Content-Length: 41637
X-Content-Type-Options: nosniff
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: image/jpeg
````

And the request headers are:

````
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: _ga=GA1.3.786170704.1600091517; _gid=GA1.3.590880272.1606221307; _pk_ses.5.14ad=1; TotaraSession=q7sdkhkbbjhaims1km0idk4vkv; TOTARAID_=EE%25D4%2583%2595; _gat=1; _pk_id.5.14ad=a8823e97c2059f70.1600091519.69.1606302304.1606232259.
Host: v12.jameslocalhost.local
Pragma: no-cache
Referer: https://v12.jameslocalhost.local/course/view.php?id=50
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
````

So I think that maybe this is an issue with Core because it's forcing conversion to PNG if available without checking file mimetype.

**Comment by gjb2048** [comment]
@jamestombs You have to be kidding!!!!  You're using a version of the Grid format designed for Moodle 2.9 on effectively Moodle 3.3 and you're asking for support!  Why are you not using the version of Grid for Moodle 3.3?  And you've also changed the code, so how can I support something that's changed?

M3.9 version with create_section_image uses generate_image_thumbnail which calls resize_image which calls imagecreatefromstring (https://www.php.net/manual/en/function.imagecreatefromstring.php).  I'll briefly look at the M3.3 version of the code.

**Comment by gjb2048** [comment]
The 3.3 version does ensure that the file record has the correct mime type for serving: https://github.com/gjb2048/moodle-format_grid/blob/MOODLE_33/lib.php#L2167-L2180.

**Comment by gjb2048** [comment]
So does the M2.9 version -> https://github.com/gjb2048/moodle-format_grid/blob/MOODLE_29/lib.php#L1318-L1331 - so is your GD Lib up to date?

**Comment by jamestombs** [comment]
As I said, it's the latest version that works with Totara (a fork of Moodle but codebases diverged a long time ago) so we sort of have our hands tied about what we can do. The code you've highlighted in Grid is the same in the version we have.

The issue I think is that eventually the function resize_from_image function is called which immediately chooses PNG if imagepng function exists - https://github.com/moodle/moodle/blob/c8d33eb9ceac63135723891d357e59dee6f5d76a/lib/gdlib.php#L332-L343 - ignoring the original mimetype then Grid applies the original mimetype which in this case is wrong as Moodle has converted to a PNG.

**Comment by gjb2048** [comment]
I don't use that -> https://github.com/gjb2048/moodle-format_grid/blob/MOODLE_29/lib.php#L1554-L1702.

**Comment by gjb2048** [comment]
@jamestombs Ok, as this is all very old on versions that I no longer update / support, I'm calling it quits here unless paid for my time.  If there is a bug in the M3.9 version (at this time) then I'll look at it.

**Comment by jamestombs** [comment]
That's fair enough. I've just checked latest and as you say it's fine and image mimetype is correctly maintained throughout conversion. Thanks for your persistence.
