### ISSUE TITLE
moodle 3.10 / grid format 3.10.0.1 / "Show new activity notification image default"  option : not functionning well

### ISSUE THREAD

**Issue by kbblue** [gjb2048/moodle-format_grid#130]
Hello,
I am using moodle 3.10 and the last version of grid format (3.10.0.1).
Everything was working fine when I saw something appearing on my images (different in editing and visualizing modes -web).
When I tried to understand, I realized that there was an option ("Show new activity notification image default") selected by default to yes.
I thought, I would have just to set it to no and get back to normal.
But I realized that the notifications stayed anyway and were different from one view (only the first image tagged) to another (four images tagged) as you can see in the two screenshots below.
first screenshot : [url=https://ibb.co/mqMm2XP][img]https://i.ibb.co/58fdSnJ/Screenshot-in-editing-mode.png[/img][/url]
second screenshot : [url=https://ibb.co/t4K6d36][img]https://i.ibb.co/6mwSdNS/Screenshot-in-web-mode-anonymous.png[/img][/url]

May be I missed something.
Any help would be great.
Thank you in advance.

**Comment by gjb2048** [comment]
Its Saturday!  Get a life!!!

**Comment by kbblue** [comment]
Hello gjb2048,
I am taking that comment as a joke...
I am a teacher at university and as you know (or may be not !!!) we often work out of office hours to get ready during classes.
 thank you anyway.
P. Kryzine, Ph.D.

**Comment by gjb2048** [comment]
@kbblue Sorry, but I'm being serious.  I was a teacher so understand the hours involved.  However I need a break from this.  I am maintaining the format, but unless it is a serious issue in the code that is my mistake then I'm giving myself a rest as I'm physically and mentally knackered.  If you still need me to spend my time, then kindly read: https://github.com/gjb2048/moodle-format_grid#support.

**Comment by kbblue** [comment]
@gjb2048. Sorry too. I didn't mean to bother you and I didn't send the issue saying I was in a hurry.
It is up to you to see if it is a mistake in the code or not. For the records, I was also coding software before ....
Don't worry, I just have to get rid of this plugin and get back to the standard view. It is less appealing but I will not have to read messages like yours ...
Have a great week-end and take a rest please. Life is better when people like each others.

**Comment by kbblue** [comment]
@gjb2048. I uninstalled the plug-in and got back to normal. Thank you for your advice; I'm going to get my life back. Going out for a break. The issue is closed for me. sorry for disturbing you (I am sincere).
