### ISSUE TITLE
Can´t upload jpg image as course image grid

### ISSUE THREAD

**Issue by ahmadShiyarHesso** [gjb2048/moodle-format_grid#131]
I am running Moodle 3.9.1 (Build: 20200713) on my server and have the following issue:

I changed the course format to grid and tried to upload an image(login.jpg) to a topic and got this error : 

Format is not supported at this server, please fix the system configuration to have the GD PHP extension installed - JPG, itemid &gt; 25, filename &gt; goi_login.jpg, sectionimage_sectionid &gt; 25, sectionimage_image &gt; goi_login.jpg, sectionimage_newimage &gt; goi_login.jpg and sectionimage_displayedimageindex &gt; 0. Please report error details and the information contained in the php.log file to developer.

error/format grid/formatnotsupported

I did some research but I couldn´t find a solution 

you may use the following information
Grid version: 2020070701(3.9.1.0)
Server Software: nginx
php version : 7.2.12
GD support: active 
GD version: bundled(2.1.0 compatible)

Thank you  😀

**Comment by gjb2048** [comment]
Is the PHP GD extension installed and enabled?

**Comment by ahmadShiyarHesso** [comment]
Yes it is. You can find specifications in the bottom section of the first message

**Comment by gjb2048** [comment]
I saw that, however is it appearing as such to PHP, i.e. phpinfo() that you can see on the Admin server settings etc.

**Comment by ahmadShiyarHesso** [comment]
Exactly, this is from phpinfo()

**Comment by gjb2048** [comment]
Ok, so does yours look like:

![gd_lib](https://user-images.githubusercontent.com/1058419/103241896-725d6e80-494c-11eb-91fa-55b5305a810b.PNG)


?  And is it actually a JPEG file?

**Comment by ahmadShiyarHesso** [comment]
![2020-12-29](https://user-images.githubusercontent.com/58402886/103283155-0e808780-49d8-11eb-9f14-629b833c5fac.png)

**Comment by gjb2048** [comment]
It might have a jpg extension, but is it really a JPEG?  And why does your GD lib not have JPEG support enabled?

**Comment by ahmadShiyarHesso** [comment]
I looked in the file properties and it says jpg file. How can I enable JPEG support?

**Comment by gjb2048** [comment]
Google it!!!

**Comment by ahmadShiyarHesso** [comment]
Problem solved! Thank you for your help!

**Comment by gjb2048** [comment]
@ahmadShiyarHesso What was the issue please?

**Comment by ahmadShiyarHesso** [comment]
It was just like you said I just had to enable jpeg support. I have docker installed for my server and i'm new to this so it toke me time to install and enable Jpeg support properly but eventually it worked.
