### ISSUE TITLE
The content of general section is shown in every grid

### ISSUE THREAD

**Issue by hirvota** [gjb2048/moodle-format_grid#132]
In the grid format you can move the general section (section 0) into grid.  We found a bug in the latest release 3.9.1.0.  

If the general section is moved into the grid its content is shown in every grid/section. This appears in non-editing mode when opening the grids. This is an unwanted feature.

**Comment by gjb2048** [comment]
Cannot replicate.  Evidence please.

**Comment by gjb2048** [comment]
@hirvota If you can't prove this, then I can't help you.

**Comment by hirvota** [comment]
Hi,

we found the reason. It was due to our own modification. This issue can be closed. Thank you for your patience, Gareth.
