### ISSUE TITLE
Duplicated section name

### ISSUE THREAD

**Issue by golenkovm** [gjb2048/moodle-format_grid#134]
Hi,

Just found a bug that duplicates a section name in Moodle 3.9.

Steps to replicate:
- Create a course with Grid format;
- Set layout to one section per page;
- Turn editing on;
- Move General section into grid;
- Open any section.

Screenshot:
![image](https://user-images.githubusercontent.com/22066290/106830404-29829d80-66e2-11eb-8448-054364e3e50f.png)

Replicated with Moodle 3.9 and master with boost theme.

**Comment by golenkovm** [comment]
This works fine with Moodle 3.7 and 3.8

**Comment by golenkovm** [comment]
Hi @gjb2048 

I've done some research how does it look like in 3.8 and 3.9.

**Moodle 3.8:**
All sections on one page layout:
* Linkable and editable section names with dots.

One section per page layout:
* With general section: Not linkable, but editable section name without dots.
* Without general section: Not linkable and not editable section name without dots.

**Moodle 3.9:**
All sections on one page layout:
* Linkable and editable section names with dots.

One section per page layout:
* With general section: Not linkable, but editable section name without dots.
* Without general section: (**here the bug appears**) Not linkable and not editable section name without dots **PLUS** linkable and editable section names with dots.

From my point of view, not linkable and not editable section name without dots should be removed from one section per page layout with general section moved into grid.

Cheers
Mikhail

**Comment by golenkovm** [comment]
This looks to be a regression of https://github.com/gjb2048/moodle-format_grid/commit/3db48d5d258215ab5b4ec05212d87835053575e6

**Comment by golenkovm** [comment]
Hey @gjb2048 

Could you please have a look at the pull requests that I've created.
Feel free to let me know if you think this should be fixed in another way.

Cheers,
Mikhail

**Comment by gjb2048** [comment]
Dear Mikhail,

Will look as soon as I can.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Patches are incomplete.  Is actually a misplacement of the 'id' -> https://github.com/gjb2048/moodle-format_grid/commit/3db48d5d258215ab5b4ec05212d87835053575e6#diff-e82e7ce1e17af09c0cd0f5fee5930434efabb50487fa59a889bc3ba36503c1b8R244.

**Comment by gjb2048** [comment]
Far more complex than anticipated -> https://github.com/gjb2048/moodle-format_grid/commit/3c73a292767f015a3ef72d266d111c1cb4bb140f

**Comment by golenkovm** [comment]
Hi @gjb2048 
Seems like your patch does what it's supposed to do.
Thank you

**Comment by gjb2048** [comment]
@golenkovm Sorry I couldn't accept your patches, removing the section title there was not the whole story.

**Comment by golenkovm** [comment]
No worries @gjb2048 
Thank you for quick response and fixing the issue.
I think this can be closed now.
Cheers
