### ISSUE TITLE
Grid format and performance/ blackfire.io

### ISSUE THREAD

**Issue by danbuntu** [gjb2048/moodle-format_grid#14]
![grid-format-blackfire](https://cloud.githubusercontent.com/assets/688626/7347569/c89457d2-ece1-11e4-9df1-2558f249744f.png)
Hello

I've recently been playing with blackfire.io and noticed that on a moodel course that uses the grid format that black fire shows a significant part of the loading times is becuase of grid format. I wonder if this info was relevant and perhaps something that could be looked into.

Please see the attached image that a page load on one of my sample courses where the grid format takes 42% of the load time, in particular the make_block_icon_topics function

**Comment by gjb2048** [comment]
Thanks for the info.  The chart shows the 'print_r' function taking 26...%.  That will only happen when debugging is turned on.

**Comment by gjb2048** [comment]
P.s Please could you provide the steps I need to take to replicate this, then I'll be able to verify that any changes I make actually improve things.

**Comment by danbuntu** [comment]
I've just checked this on my live system as well and I get the same results. 

Moodle debugging is turned off on this system and display_errors set to off in php.ini. I've also doubled checked debug isn't on in my config.php

My setup is:

ubuntu 14.04
moodle 2.7.5
grid format 2.7.2

into that I've installed blackfire as per the instructions as at blackfire.io

**Comment by gjb2048** [comment]
Ta.  V2.7.2.1 is the latest for M2.7 to check against.

**Comment by gjb2048** [comment]
Odd: https://github.com/gjb2048/moodle-format_grid/blob/MOODLE_28/lib.php#L1291-L1295

**Comment by danbuntu** [comment]
yes I noticed that.

I've just re-run the blackfire tests on my live system and I'm not getting the print_r section. I am still seeing a good part of the course load times coming from the grid format though. 

I tried to screenshot it but it's a right spiders web :-)

**Comment by gjb2048** [comment]
So, any specific place you think it could be improved?

**Comment by danbuntu** [comment]
course_section_cm seems to account for 23% of the load time according to blackfire so possibly that one.

**Comment by gjb2048** [comment]
That's a core API method.

**Comment by danbuntu** [comment]
Lets close this and

**Comment by danbuntu** [comment]
Lets close this then and i'll re-open if I come up with some thing more concrete at some point

**Comment by gjb2048** [comment]
Ok.
