### ISSUE TITLE
AMOS

### ISSUE THREAD

**Issue by dinism** [gjb2048/moodle-format_grid#140]
Thanks a lot for the plugin.
I'm PT-PT translator.

The strings included in the commit [2930d9f ](https://github.com/gjb2048/moodle-format_grid/commit/2930d9f0186920f15b78ac35c7b58163d1c49f34#diff-9249b7dd492fb7692f765536be30bfe116c231699ce13073534c7e2936c2ea71)don't appear in AMOS.

**Comment by gjb2048** [comment]
Given https://moodle.org/plugins/format_grid/3.10.1.1/24136 and that they are not appearing in AMOS, please raise a Moodle Tracker issue (possibly MDLSITE) as to why.  This mechanism is outside of my control.

**Comment by dinism** [comment]
OK. Sorry about my issue.
