### ISSUE TITLE
Grid images are misplaced in Right-to-left (RTL) mode

### ISSUE THREAD

**Issue by acquaalta** [gjb2048/moodle-format_grid#141]
Moodle version: 3.10
Theme: Boost
Grid format plugin version: 3.10.1.1

Hi,
While Using the Grid format in a course and the editing mode is on, I added a photo to a course section ("Change image" link/button) in RTL mode, and it seems that it is misplaced in the section area. When switching to  Left-to-right (LTR) mode, the image seems to be placed correctly.

I didn't encounter this issue before. In Moodle v3.8.2 with Grid format v3.8.0.1 (2019111700), everything seems to be right.

This is a serious issue for RTL users, and in fact prevents them from using this format.
Could you please fix this issue? 
Thanks :-)

![gridformat_RTLissue](https://user-images.githubusercontent.com/51836675/118491942-2ad35580-b728-11eb-84ff-52f779cbe826.jpg)

**Comment by gjb2048** [comment]
See: https://github.com/gjb2048/moodle-format_grid/commit/41a719b4ca372442cc526e0fe7ed705b9d2144e3.
