### ISSUE TITLE
Course restore fails with `cannotgetimagesforcourse` error

### ISSUE THREAD

**Issue by chrisfosterelli** [gjb2048/moodle-format_grid#145]
We installed plugin version 3.10.1.3 into a fresh install of Moodle 3.10.4+. When attempting to restore a course that uses the grid plugin, it raises the following error during the import: `Cannot get images for course.  Please report error details to developer.`

From what I understand the course exports would have been generated from Moodle 3.9 with a 3.9 version of the plugin from the last year or so, but I'm not sure which versions specifically. They are private IP so I unfortunately cannot share a specific export file without their permission, but all courses we attempted to import failed.

Uninstalling the plugin and installing version 3.10.1.2 made the course restore process work again.

I looked through the issues and couldn't find anything directly related, but possibly is related to the recent https://github.com/gjb2048/moodle-format_grid/issues/144 

Thanks for your work on this plugin! Lots of our installs make use of it and this is the first time an issue has ever come up. Let me know if you need any specific info and I can try to ask the course developer.

**Comment by gjb2048** [comment]
@chrisfosterelli Version 3.10.1.3 (a release candidate version) specifically will have an issue on clean installs as I know about a bug where I've not added in a new field in the DB, hence the error.  This will be fixed in the next version.

**Comment by chrisfosterelli** [comment]
@gjb2048 Great, thanks! Yeah I think the person who downloaded it didn't notice it was an RC, the Moodle download page doesn't make that super clear. Thanks for the info.

**Comment by gjb2048** [comment]
Correction, I had added the field -> https://github.com/gjb2048/moodle-format_grid/blob/master/db/install.xml#L12 - humm!

**Comment by gjb2048** [comment]
Really odd, can replicate on a clean M3.10 but not my dev install even though identical!

**Comment by gjb2048** [comment]
Fixed I hope!

**Comment by gjb2048** [comment]
Released: https://moodle.org/mod/forum/discuss.php?d=424140.
