### ISSUE TITLE
Fatal upgrade error if section image could not be found in filestorage

### ISSUE THREAD

**Issue by PM84** [gjb2048/moodle-format_grid#146]
If a file can be found in the DB, but for whatever reason it cannot be found in the filestorage, the following error is currently thrown during an upgrade:

`-->format_grid
PHP Warning: copy(/srv/shared/moodle-dlb/moodledata/filedir/a1/10/a1104606c11ea0c78dd28df724197d8779e44754): failed to open stream: No such file or directory in /srv/shared/moodle-dlb/html/lib/filestorage/file_system_filedir.php on line 234
PHP Warning: getimagesize(/srv/shared/moodle-dlb/moodledata/temp/gridformatdisplayedimagecontainer/a1104606c11ea0c78dd28df724197d8779e44754): failed to open stream: No such file or directory in /srv/shared/moodle-dlb/html/course/format/grid/classes/toolbox.php on line 1013
PHP Warning: unlink(/srv/shared/moodle-dlb/moodledata/temp/gridformatdisplayedimagecontainer/a1104606c11ea0c78dd28df724197d8779e44754): No such file or directory in /srv/shared/moodle-dlb/html/course/format/grid/classes/toolbox.php on line 1016
Database transaction aborted automatically in /srv/shared/moodle-dlb/html/admin/cli/upgrade.php
Default exception handler: Fehlende Bildinformation - itemid &gt; 19930, filename &gt; goi_Zeichenfläche 1 Kopie.png, sectionimage_sectionid &gt; 19930, sectionimage_image &gt; goi_Zeichenfläche 1 Kopie.png, sectionimage_newimage &gt; goi_Zeichenfläche 1 Kopie.png and sectionimage_displayedimageindex &gt; 1.  Melden Sie bitte die Fehlerdetails und die Information aus der Datei php.log dem Entwickler. Debug: generate_image
Error code: noimageinformation
* line 498 of /lib/setuplib.php: moodle_exception thrown
* line 1017 of /course/format/grid/classes/toolbox.php: call to print_error()
* line 789 of /course/format/grid/classes/toolbox.php: call to format_grid\toolbox::generate_image()
* line 983 of /course/format/grid/classes/toolbox.php: call to format_grid\toolbox::setup_displayed_image()
* line 640 of /course/format/grid/classes/toolbox.php: call to format_grid\toolbox::update_displayed_images()
* line 1825 of /course/format/grid/lib.php: call to format_grid\toolbox::update_displayed_images_callback()
* line 149 of /course/format/grid/db/upgrade.php: call to format_grid::update_displayed_images_callback()
* line 697 of /lib/upgradelib.php: call to xmldb_format_grid_upgrade()
* line 1922 of /lib/upgradelib.php: call to upgrade_plugins()
* line 193 of /admin/cli/upgrade.php: call to upgrade_noncore()

!!! Fehlende Bildinformation - itemid &gt; 19930, filename &gt; goi_Zeichenfläche 1 Kopie.png, sectionimage_sectionid &gt; 19930, sectionimage_image &gt; goi_Zeichenfläche 1 Kopie.png, sectionimage_newimage &gt; goi_Zeichenfläche 1 Kopie.png and sectionimage_displayedimageindex &gt; 1.  Melden Sie bitte die Fehlerdetails und die Information aus der Datei php.log dem Entwickler. !!!
!! generate_image
Error code: noimageinformation !!
!! Stack trace: * line 498 of /lib/setuplib.php: moodle_exception thrown
* line 1017 of /course/format/grid/classes/toolbox.php: call to print_error()
* line 789 of /course/format/grid/classes/toolbox.php: call to format_grid\toolbox::generate_image()
* line 983 of /course/format/grid/classes/toolbox.php: call to format_grid\toolbox::setup_displayed_image()
* line 640 of /course/format/grid/classes/toolbox.php: call to format_grid\toolbox::update_displayed_images()
* line 1825 of /course/format/grid/lib.php: call to format_grid\toolbox::update_displayed_images_callback()
* line 149 of /course/format/grid/db/upgrade.php: call to format_grid::update_displayed_images_callback()
* line 697 of /lib/upgradelib.php: call to xmldb_format_grid_upgrade()
* line 1922 of /lib/upgradelib.php: call to upgrade_plugins()
* line 193 of /admin/cli/upgrade.php: call to upgrade_noncore()
 !! `

A possible Solution is the pull request: #147

**Comment by gjb2048** [comment]
@PM84 Thanks for the info and patch, but I've already solved this in #143.
