### ISSUE TITLE
Observer throws error on course restore format_{name}::get_contextid() 

### ISSUE THREAD

**Issue by amandadoughty** [gjb2048/moodle-format_grid#149]
Hi Gareth, we are getting an error which is sort of specific to us. 

To give you some background to make sense of the stack trace below: We have a plugin which allows users to rollover content from one course to another. It uses the moodle core back up and restore functionality. The core restore code triggers a 'course_restored' event, which is observed by Grid format. When our backed up course uses Grid format but our destination course uses another format (in this case our own). Then we get the error. You can see it is caused by a call to a function that does not exist other course formats - classes/toolbox.php #935

$courseformat = course_get_format($courseid);
$contextid = $courseformat->get_contextid();

Scheduled task failed: Rollover processing (local_culrollover\task\rollover_task),Call to undefined method format_culcourse::get_contextid()
Backtrace:
* line 70 of /course/format/grid/classes/observer.php: call to format_grid\toolbox::delete_images()
* line 63 of /course/format/grid/classes/observer.php: call to format_grid_observer::delete_images_and_summary()
* line ? of unknownfile: call to format_grid_observer::course_restored()
* line 155 of /lib/classes/event/manager.php: call to call_user_func()
* line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
* line 834 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
* line 195 of /backup/util/plan/restore_plan.class.php: call to core\event\base->trigger()
* line 394 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
* line 425 of /local/culrollover/classes/rollover.php: call to restore_controller->execute_plan()
* line 126 of /local/culrollover/classes/rollover.php: call to local_culrollover\rollover->copy_course()
* line 62 of /local/culrollover/classes/task/rollover_task.php: call to local_culrollover\rollover->copy_courses()
* line 248 of /lib/cronlib.php: call to local_culrollover\task\rollover_task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 79 of /admin/cli/cron.php: call to cron_run()

Using v3.9.1.4 on Moodle v3.9.10

**Comment by gjb2048** [comment]
@amandadoughty Noted, will look when I get the chance.

**Comment by gjb2048** [comment]
@amandadoughty I've looked at the code and now understand what is going on.  The code does need to react to the event as it needs to delete the images as it was a Grid course.  But... just need to make the methods static in some way so that the logic works but can adapt to a course id being passed in or still using an object instance one.

**Comment by amandadoughty** [comment]
Thank you. I totally understand. We can work around it until you get time.

**Comment by gjb2048** [comment]
@amandadoughty I've not forgotten about this, honest!

**Comment by gjb2048** [comment]
@amandadoughty Please test patch: https://github.com/gjb2048/moodle-format_grid/commit/9914d6972c59a3d633a8d66af134aeb771d5a360 - I have been able to replicate.

**Comment by gjb2048** [comment]
Note to self:  Backport to M3.8 version.

**Comment by gjb2048** [comment]
@amandadoughty No problem, was my bug.

**Comment by phette23** [comment]
Thanks, @amandadoughty for writing a comprehensive bug report, it took me forever to figure out what was happening but it looks like we are also running into this issue, for the same reason I suspect (are you using [local_course_template](https://moodle.org/plugins/local_course_template)?).

When might this patch be included in a release? And how we might work around the issue until then? Will the plugin work if I just apply this patch (we're on the latest release)? Thanks for your work on this plugin @gjb2048.

**Comment by gjb2048** [comment]
@phette23 I'll do a release at some point.

**Comment by gjb2048** [comment]
Backported to M3.9.
