### ISSUE TITLE
Pointless try...catch block in setup_displayed_image() (lib.php)

### ISSUE THREAD

**Issue by thepurpleblob** [gjb2048/moodle-format_grid#15]
The very big try...catch block in this function seems pointless. It doesn't do anything to recover from a problem it just masks the actual error if something goes wrong. The actual error messages that are peppered throughout the try{} block will likely never be called. The much less specific ones in the catch{} block will be preferred.

**Comment by gjb2048** [comment]
Thanks for the info Howard, what changes do you suggest?

**Comment by thepurpleblob** [comment]
I would just take it out. 

I must admit that I can be on a bit of a mission about try...catch. IMO it serves no purpose (other than to mask error reporting) unless it actually does something to recover from potential errors. In this case it just shows some generic errors. It would be much better to catch any errors at the source line. The display will be broken either way.

**Comment by gjb2048** [comment]
Good point :) - I'll have a bash probably sometime in June after iMoot.
