### ISSUE TITLE
Question: 3.11 compatibility?

### ISSUE THREAD

**Issue by webframp** [gjb2048/moodle-format_grid#150]
Greetings, thanks for your work on this plugin. 

I was wondering when a new release with 3.11 compatibility might be released? Didn't already see any open or closed issues tagged for it, so I thought I'd ask.

Thanks!

**Comment by gjb2048** [comment]
Hi Sean,

Good question, not sure yet, will be at some point.

Kind regards,

Gareth

**Comment by webframp** [comment]
Wonderful. Thanks for keeping it going!

I can confirm for now that the latest 3.10 release appears to work ok with at least 3.11.3+ (Build: 20210924)

**Comment by gjb2048** [comment]
https://moodle.org/mod/forum/discuss.php?d=430833

**Comment by gjb2048** [comment]
Please see: https://moodle.org/mod/forum/discuss.php?d=430833#p1733883.
