### ISSUE TITLE
format_base deprecated in Moodle 4.0

### ISSUE THREAD

**Issue by nwp90** [gjb2048/moodle-format_grid#151]
Not sure whether 4.0 will be the first release in which this is deprecated, but in current master (dev for 4.0), the following is logged:

[14-Oct-2021 15:05:57 Pacific/Auckland] Debugging: Class 'format_base' has been renamed for the autoloader and is now deprecated. Please use 'core_courseformat\base' instead. in 
* line 141 of /lib/classes/component.php: call to debugging()
* line ? of unknownfile: call to core_component::classloader()
* line 33 of /course/format/grid/lib.php: call to spl_autoload_call()
* line 864 of /lib/classes/component.php: call to include_once()
* line 7791 of /lib/moodlelib.php: call to core_component::get_plugin_list_with_file()
* line 247 of /lib/externallib.php: call to get_plugins_with_function()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

There might well be more warnings once that one is fixed - happy to help fix, if you have a branch or otherwise know how you'd like to manage the relevant code.

**Comment by gjb2048** [comment]
Dear Alistair,

Thanks for asking, thinking about this at the moment as complex and have
been learning new skills to potentially shine a light on the answers to
your questions.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
@aspark21 As M4.0 version has now been created, this is not an issue.

**Comment by octavio-meneghetti** [comment]
estoy instalando la version 4.4.1 de moodle y me salta este error y no abre ni el administrador Error
Excepción - Class "format_base" not found  alguien sabe como arreglarlo?

**Comment by gjb2048** [comment]
@octavio-meneghetti  What version of Grid?

**Comment by octavio-meneghetti** [comment]
No se y ya no puedo entrar como la descubro?

**Comment by gjb2048** [comment]
@octavio-meneghetti Look in course/format/grid/version.php.

**Comment by octavio-meneghetti** [comment]
// Plugin version.
$plugin->version = 2021102703;

**Comment by octavio-meneghetti** [comment]
la renombré a la carpeta de grid pero no dio resultado

**Comment by gjb2048** [comment]
@octavio-meneghetti That's the version for Moodle 4.0, install the version for Moodle 4.4 -> https://moodle.org/plugins/format_grid/404.1.0/32324.

**Comment by gjb2048** [comment]
@octavio-meneghetti When you have the code, follow https://github.com/gjbarnard/moodle-format_grid/blob/main/Readme.md#upgrade-instructions.
