### ISSUE TITLE
Error: Class 'format_grid\output\completion_info' not found (Moodle 3.11.4 vs 973db4708dfa459ea683ecbda4209ece1dfd13f1)

### ISSUE THREAD

**Issue by knarzhupe** [gjb2048/moodle-format_grid#152]
Hi Gareth,
it has been reported to us that in Moodle 3.11.4 grid does not work correctly. If a student (but not a trainer or above) tries to access a grid tile the correspondig link will not work and access furthermore fails with:
Error: Class 'format_grid\output\completion_info' not found

Maybe this is related to the latest changes to the completion api in moodle or to your latest changes to renderer.php or both.

Thanks for all your contributions to Moodle!

All the best,

Michael

**Comment by knarzhupe** [comment]
I digged deeper into the code, and found out that adding two use instructions to classes/output/renderer.php may fix partially. There might be better/more systemic or global approaches though; i am not that familar with the api.
These instructions may resolve partially:
use completion_info;
use url_select;

Unfortunateley there is another issue, in that popup(popover?)-sections won't open. The admin role can still access the popovers whereas as student a click on a tile does not do anything at all.

**Comment by knarzhupe** [comment]
Maybe i mixed up popovers and popups. I found out that the underlying problem maybe worked around by setting 'Show one section per page' in course settings.

**Comment by gjb2048** [comment]
@knarzhupe Do you mean what the grid boxes activate?

**Comment by gjb2048** [comment]
@knarzhupe Also, the M3.11 version has not been released yet.  What version of Grid are you using?

**Comment by knarzhupe** [comment]
from version.php:
```
$plugin->version = 2021102700;                                                                                            
$plugin->requires  = 2021051700.00; // 3.11 (Build: 20210517).                                                            
$plugin->supported = array(311, 311);                                                                                     
$plugin->release = '3.11.1.0';

```
from git log:
```
commit 973db4708dfa459ea683ecbda4209ece1dfd13f1
Author: Gareth Barnard <1058419+gjb2048@users.noreply.github.com>
Date:   Wed Oct 27 17:23:09 2021 +0100

    V3.11.1.0

```

I must admit i am not familar with format grid on daily base. If grid boxes are sort of popup-a-likes in which the section content is displayed on click then i am talking bout grid boxes in fact.

**Comment by gjb2048** [comment]
Please see: https://moodle.org/mod/forum/discuss.php?d=430833#p1733883.
