### ISSUE TITLE
Class 'format_grid\output\core_text' not found

### ISSUE THREAD

**Issue by cmonnet76** [gjb2048/moodle-format_grid#153]
Hello,

I use format_grid 3.11.1.0 (2021102700) with Moodle 3.11.4+ (Build: 20211116).
If i choose the option "Position de l'option de la boite de titre de section = intérieur", i get the error : 
"Exception : Class 'format_grid\output\core_text' not found"

Christine

**Comment by gjb2048** [comment]
V3.11.1.0 is currently in development.

**Comment by cmonnet76** [comment]
Ok. Sorry.
Is the last stable branch : MOODLE_310 ?

**Comment by gjb2048** [comment]
Yes at the time of typing.

**Comment by cmonnet76** [comment]
Thank you.
Sorry for the inconvenience

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-format_grid/commit/a111aa6969183cd8aa46e8961a60da30834630ab.

**Comment by gjb2048** [comment]
Please see: https://moodle.org/mod/forum/discuss.php?d=430833#p1733883.
