### ISSUE TITLE
Grid format is created only on irregular basis

### ISSUE THREAD

**Issue by fg9871** [gjb2048/moodle-format_grid#154]
Hello dear Grid Team,
we have encountered two problems with the grid layout in our Moodle version 3.9.5.

1.) When you change a filled course from topic format to grid format, it happens that no grid is created and the content is only visible when you edit the page. We have tested it through with several courses and the problem seems to occur completely randomly.

2.) The second problem occurs when you use the "move to grid" function and switch back to the topic format from the grid. In this case all activities are filed in the first section. 

I am grateful for any help.

With best regards, Florian

**Comment by gjb2048** [comment]
"Move to grid" is about moving section 0 in and out of the grid, so I'm confused, please state the exact steps to replicate.  Plus Grid version.  Any idea about the randomness?  Is there something special about the courses that it occurs on?  When you restore a backup from a course that has the issue on a test server, then does the problem happen again?

**Comment by gjb2048** [comment]
Please supply more evidence / reliable replication instructions or I will close this.

**Comment by AntonT76** [comment]
Dear @gjb2048,
we will provide more information, but it will take a few more days.
br, Anton

**Comment by fg9871** [comment]
Dear @gjb2048,
first of all, thank you for the quick response to our problem! To answer your questions:

**"Move to grid" is about moving section 0 in and out of the grid, so I'm confused, please state the exact steps to replicate.**

Exact steps for replication:
1.	Login to your moodle platform.
2.	Go to any moodle course which is currently on the topics format and should be changed to a grid format.
3.	Click on the course settings to open the drop down menu.
4.	Click on edit settings.
5.	Scroll down to course format
6.	Change the format setting from topic to grid
7.	Skip the rest of the settings
8.	Click save and return.
9.	When your now back in your course, the grid format does not show up. You can see the content of the course only when you turn editing on.
10.	We clicked on the function “move to grid”, to see if something changes.
11.	Unfortunately it looked the same.
12.	When we now switched back to the topics format (same procedure), the topics format was restored again, but the problem is that all of the activities from all the section moved to section 1.

**Plus Grid version.**
We used the GRID: 3.9.1.1 (2020070702)
Updated to GRID 3.9.1.4 (2020070705) - but problem still occurs.

**Any idea about the randomness?**
Well we think it has something to do with the course size, but we are not sure. Like I mentioned in my request, we tried it with filled courses. The courses had different sizes. What I mean by size is that we tried it with courses that had 3 sections with only a few activities, like one or two documents and maybe an assignment per section. But we also tried it with bigger courses which had 8 sections with four to five documents and several other activities like assignments, forum etc. per section. If it worked once, then it was rather smaller courses, however, we had problems with those too.

**When you restore a backup from a course that has the issue on a test server, then does the problem happen again?**
Yes, we restored a backup from a course on a test server, but the problem occurred also there.

For further information we don’t use the newest moodle version – we still use the version 3.9.5 – so maybe the bug is fixed on newer moodle versions. Please note that we will not respond until the 10th of January, bc. of the Christmas holidays. If you have any advices by then we will try it and give you feedback. Thank you in advance!

Best regards,
Florian

**Comment by gjb2048** [comment]
Dear Florian (@fg9871),

The readme states 'Before reporting an issue, please ensure that you are running the latest version for your release of Moodle.' therefore I will double check on Moodle 3.9.11+ and to be realistic, 3.9.11 which is the last formal release.  However as you're running 3.9.5, then that is much more time for me and I'd want to be paid for it, i.e. 'support' -> https://github.com/gjb2048/moodle-format_grid#support.

Kind regards,

Gareth

**Comment by fg9871** [comment]
Dear Gareth @gjb2048,

ok thank you for the advice, I'll keep it in mind for the next time. We are going to update our moodle version but we do not have a particulare date for the update. So as soon as we have updated to 3.9.11+ we will check if the bug occurs again, if so, we will reopen the ticket.

Best regards,
Florian

**Comment by fg9871** [comment]
Dear Gareth @gjb2048,

We have updated to our moodle version to 3.9.12 and everything works fine. Thank you.

Best regards,
Florian
