### ISSUE TITLE
Exception : Class 'format_grid\output\stdClass' not found

### ISSUE THREAD

**Issue by gjalam** [gjb2048/moodle-format_grid#156]
Hello,
I have this error after updating to the last version this morning:

Exception : Class 'format_grid\output\stdClass' not found

Plus d'informations sur cette erreur

×Info de débogage 
Error code: generalexceptionmessage
×Trace de la pile 
line 291 of /course/format/grid/classes/output/renderer.php: Error thrown
line 268 of /course/format/grid/classes/output/renderer.php: call to format_grid\output\renderer->single_section_page_summary()
line 391 of /course/format/grid/classes/output/renderer.php: call to format_grid\output\renderer->section_header_onsectionpage()
line 254 of /course/format/grid/format.php: call to format_grid\output\renderer->print_single_section_page()
line 278 of /course/view.php: call to require()

Can you help me to fix this ?
I am with Moodle 3.11.4+

Regards,
Gabriel

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-format_grid/commit/3d8502969ed339e36e81203067fda95883e4a83e

**Comment by gjb2048** [comment]
Please see: https://moodle.org/mod/forum/discuss.php?d=430833#p1733883.
