### ISSUE TITLE
PHP 8.0 error when uploading image to grid element

### ISSUE THREAD

**Issue by steveorulez** [gjb2048/moodle-format_grid#163]
Hello, 

when uploading an image on a grid element I get this error (PHP 8.0)

![image](https://user-images.githubusercontent.com/4101369/175558379-0bf34785-ee8c-4f44-89b5-80e9bf16499f.png)

From 8.0 you can't pass more arguments to a function? They changed from warning to error? I couldn't find any information on this.

I tried to create a short php7.4 example on my local machine and if I pass 4 arguments to imagejpeg no error or warning come out
If i pass 5 elements this "Warning" come out:
Warning: imagejpeg() expects at most 4 parameters, 5 given 

If i do the same thing on php 8.0 with 4 arguments i get this error:
Fatal error: Uncaught ArgumentCountError: imagejpeg() expects at most 3 arguments, 4 given 

At the moment i just did a fast fix by adding this to file classes/toolbox.php line 1174 (after ob_start):
$tmpimg;
if ($imagefnc === 'imagepng') {
  $tmpimg = $imagefnc($finalimage, null, $quality, $filters);
}else{
  $tmpimg = $imagefnc($finalimage, null, $quality);
}
if (!$tmpimg) {
// removed the old call to the function
// if (!$imagefnc($finalimage, null, $quality, $filters)) {

christian

**Comment by gjb2048** [comment]
What version of Moodle / Grid format?

**Comment by gjb2048** [comment]
Also PHP 8.0 is not officially supported for Moodle - see the release notes.

**Comment by steveorulez** [comment]
Oh I didn't notice that is not officially supported, thanks for reminding me about it!

Grid Release 3.11.1.2, version 2021102702 on Moodle 3.11.7+ (Build: 20220617)

**Comment by gjb2048** [comment]
Possible solution for M4.0 version that could be backported -> https://github.com/gjb2048/moodle-format_grid/commit/243704b08d88c9dcf8828f78b6f259356dbedb0d.

**Comment by langlukas** [comment]
Hello! We get the same error on our Moodle.
Moodle: 3.11.10+ (Build: 20220930)
Grid Format: 3.11.1.2

@gjb2048 PHP 8.0 is supported since Moodle 3.11.8 https://moodledev.io/general/development/policies/php#php-80

**Comment by gjb2048** [comment]
@langlukas In that case as PHP 8.0 was added as after the major release then that's really an enhancement.  Thus as I'm no longer developing this code base of the format and this is a reasonable amount of work, then it needs to be funded.

**Comment by tthakar86** [comment]
I have taken a look and it looks like the following line of code is causing error: **1174** in the file: classes/toolbox.php inside the grid format plugin.

To fix it replace the following:
```
            if (!$imagefnc($finalimage, null, $quality, $filters)) {
                ob_end_clean();
                unlink($filepath);
                print_error('functionfailed', 'format_grid', '', $imagefnc.', '.self::debugdata_decode($debugdata), 'generate_image');
                return false;
            }

```

with this:

```
        if($imagefnc =='imagejpeg'){
            if (!$imagefnc($finalimage, null, $quality)) {
                ob_end_clean();
                unlink($filepath);
                print_error('functionfailed', 'format_grid', '', $imagefnc.', '.self::debugdata_decode($debugdata), 'generate_image');
                return false;
            }
            
        }else{
            
            if (!$imagefnc($finalimage, null, $quality, $filters)) {
                ob_end_clean();
                unlink($filepath);
                print_error('functionfailed', 'format_grid', '', $imagefnc.', '.self::debugdata_decode($debugdata), 'generate_image');
                return false;
            }
        }

```

This is just checking if the function that needs to run is imagejpeg() then only pass in 3 params and ignore the filters param.

This code is not tested fully so please use it with caution.

**Comment by gjb2048** [comment]
@tthakar86 Why? When I've already implemented a solution above (https://github.com/gjb2048/moodle-format_grid/issues/163#issuecomment-1208431336) that copes with 'imagegif' etc. only having two arguments, which your solution does not cater for.

**Comment by tthakar86** [comment]
@gjb2048  - Apologies for implementing a solution that was already created. I skim-read the thread and I didn't see the solution to this. The code I posted was just for the imagejpeg which is what we were stuck on and implemented the fix just for that part only.

Thank you for pointing that out. 😉

**Comment by gjb2048** [comment]
Released: https://moodle.org/mod/forum/discuss.php?d=443297.
