### ISSUE TITLE
Cannot get summary lock

### ISSUE THREAD

**Issue by todog** [gjb2048/moodle-format_grid#165]
Hi

I'm unable to access a course on Moodle 3.9.3 due to the following error: Cannot get summary lock. Please report error details to developer.

Error code: cannotgetsummarylock
Stack trace:
line 434 of \course\format\grid\classes\toolbox.php: moodle_exception thrown
line 63 of \course\format\grid\lib.php: call to format_grid\toolbox::get_summary_visibility()
line 53 of \course\format\grid\renderer.php: call to format_grid->is_section0_attop()
line 417 of \lib\outputfactories.php: call to format_grid_renderer->__construct()
line 2314 of \lib\outputlib.php: call to theme_overridden_renderer_factory->get_renderer()
line 874 of \lib\pagelib.php: call to theme_config->get_renderer()
line 141 of \course\view.php: call to moodle_page->get_renderer()

Stack trace:
line 434 of \course\format\grid\classes\toolbox.php: moodle_exception thrown
line 63 of \course\format\grid\lib.php: call to format_grid\toolbox::get_summary_visibility()
line 193 of \course\format\grid\lib.php: call to format_grid->is_section0_attop()
line 3322 of \course\lib.php: call to format_grid->get_view_url()
line 2128 of \lib\navigationlib.php: call to course_get_url()
line 502 of \course\format\lib.php: call to global_navigation->load_generic_course_sections()
line 2029 of \lib\navigationlib.php: call to format_base->extend_course_navigation()
line 1395 of \lib\navigationlib.php: call to global_navigation->load_course_sections()
line 3503 of \lib\navigationlib.php: call to global_navigation->initialise()
line 3548 of \lib\navigationlib.php: call to navbar->has_items()
line 4534 of \lib\outputrenderers.php: call to navbar->get_items()
line 52 of \theme\boost_campus\layout\columns2.php: call to core_renderer->region_main_settings_menu()
line 1374 of \lib\outputrenderers.php: call to include()
line 1304 of \lib\outputrenderers.php: call to core_renderer->render_page_layout()
line 2823 of \lib\outputrenderers.php: call to core_renderer->header()
line 390 of \lib\setuplib.php: call to core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()

Are you aware of any issues that may be causing this error.

I've been able to successfully restore the course from a backup.

Thanks
todog

**Comment by todog** [comment]
Further to above.

The only work around I've discovered is to disable the grid format in the database for the course.

**Comment by gjb2048** [comment]
Dear @todog,

I'm no longer supporting the M3.9 version unpaid.

Gareth

**Comment by gjb2048** [comment]
No reply, closing.
