### ISSUE TITLE
Error during exchange of section pictures

### ISSUE THREAD

**Issue by ralfhilg** [gjb2048/moodle-format_grid#168]
Moodle 4.0.4
Grid 4.0.1.0
When a teacher  wants to change an existing picture he gets an error. See attachment. 
![image001](https://user-images.githubusercontent.com/41056305/190601107-a4505543-5a9f-47c0-8fb3-e74b89efe32f.png)

**Comment by gjb2048** [comment]
Dear Ralf,

Please can you describe the exact steps that they are taking please.

G

**Comment by gjb2048** [comment]
Also, were there any other errors the first time he tried? i.e. was this the second attempt?  And is somebody else editing the same section at the same time?

**Comment by gjb2048** [comment]
Ok, can replicate.

**Comment by gjb2048** [comment]
Dear Ralf,

Please test https://raw.githubusercontent.com/gjb2048/moodle-format_grid/20fcc24baac649e2134e53af328f833126e4e014/form/sectionfilemanager.php as a direct replacement for the file you already have.

G

**Comment by gjb2048** [comment]
@ralfhilg Any news on testing this please.

**Comment by ralfhilg** [comment]
Hi Gareth
looks fine for us.

**Comment by gjb2048** [comment]
@ralfhilg Thanks for letting me know.
