### ISSUE TITLE
Table "format_grid_icon" does not exist

### ISSUE THREAD

**Issue by abkoch** [gjb2048/moodle-format_grid#170]
When changing from course format from tiles (4.0.0.8 Beta, 2022091700) to grid (400.2.0, 2022072204) with Moodle 4.0.5 (20221114) the following error occurs:

Table "format_grid_icon" does not exist

Debug-Info: 
Error code: ddltablenotexist
Stack trace: 
line 665 of /lib/dml/moodle_database.php: dml_exception thrown
line 1450 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
line 699 of /course/format/tiles/lib.php: call to moodle_database->get_records()
line 2406 of /course/lib.php: call to format_tiles->update_course_format_options()
line 191 of /course/edit.php: call to update_course()

**Comment by gjb2048** [comment]
You've not installed the format correctly, read the readme.

**Comment by abkoch** [comment]
That's what i've done (via CLI):

1. Removed grid-folder
2. Copied new grid folder
3. Activated mainentance mode
4. Run admin/cli/upgrade.php
5. Deactivated mainentance mode

**Comment by gjb2048** [comment]
Then again could be a Tiles format issue.

**Comment by gjb2048** [comment]
Bug is in the Tiles format.

**Comment by abkoch** [comment]
Thank you. Is there already an issue? Couldn't find it on https://bitbucket.org/dw8/moodle-format_tiles/issues.

**Comment by gjb2048** [comment]
I don't know.

**Comment by abkoch** [comment]
I opened a new issue: https://bitbucket.org/dw8/moodle-format_tiles/issues/141/table-format_grid_icon-does-not-exist
