### ISSUE TITLE
Grid disappears after turning edit on (Moodle 4.0)

### ISSUE THREAD

**Issue by jtuttas** [gjb2048/moodle-format_grid#171]
Hello, after we updated to Moodle 4.0 I'am not able to put images in the grid or edit the grid. When I turn Edit on, the Grid disappears !

Here is the Grid with Icons !
![off](https://user-images.githubusercontent.com/3327742/206898452-ddc583f2-820b-4ae1-b913-fad79faf9e49.png)

Here edit turned on and the Gid disappears !
![on](https://user-images.githubusercontent.com/3327742/206898459-2ed274e1-4c88-4133-8b5f-9da8bc8b4937.png)

**Comment by gjb2048** [comment]
Dear @jtuttas,

Undocumented process upgrade, turn editing on, edit section:

![Screenshot 2022-12-11 111110](https://user-images.githubusercontent.com/1058419/206900291-d1daecaa-a03a-4b3c-8690-54f3e2107d4e.png)

then upload / change the image:

![Screenshot 2022-12-11 111148](https://user-images.githubusercontent.com/1058419/206900331-ba42b12e-fe11-403f-a4e2-0f74e046db6c.png)

G

**Comment by jtuttas** [comment]
Ups thanks, sorry for the issue, so it is not a bug it is a Feature 😏
