### ISSUE TITLE
Out of frame pictures in RTL language courses

### ISSUE THREAD

**Issue by olga0601** [gjb2048/moodle-format_grid#173]
In RTL language courses **new added pictures** appear out of frame and located behind the frame.

**To Reproduce**
1. Add a new picture to a section (default pictures look ok)
2. Change the language to RTL language (arabic or hebrew)
3. See error - at the courses front page - the pictures that were changed to non-default are located out of their frames.

**Expected behavior**
Pictures to appear inside their frames and above the frame in RTL languages.

**Screenshots*
English-
![english](https://user-images.githubusercontent.com/19852616/215462197-6e565058-9447-4e63-b76f-c135e99ee4c9.PNG)
RTL language-
![arabic](https://user-images.githubusercontent.com/19852616/215462215-de52c0b5-ba22-4369-8096-7d42c3fec958.PNG)
*

**Versions (please complete the following information):**
 - Moodle: 4.1
 - Format: 401.0.1 (2022112600)
 - Browser and version Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by yaakovfendel** [comment]
created pr 174 for fixing the issue 
the fix in css is :
#page-course-view-grid.dir-rtl.format-grid .thegrid .grid-image img {
    transform: translate(50%,-50%);
}

**Comment by gjb2048** [comment]
@yaakovfendel No that is not the solution as Moodle has RTL CSS flip code that is not working for some reason.

**Comment by gjb2048** [comment]
It's on the back log, but won't be fixed soon.
