### ISSUE TITLE
Grid format - Section image - A display issue in RTL mode

### ISSUE THREAD

**Issue by acquaalta** [gjb2048/moodle-format_grid#178]
Hi,
When using Moodle in Right-to-left (RTL) mode, the section image is displayed incorrectly, off the limits of the section image frame/area. 

**Steps to reproduce the behavior:**
1. Go to to a course that uses the Grid format.
2. Add an image to a section.
3. Switch Moodle to RTL mode (by changing the UI language to Arabic, for example).

**Expected behaviour**
The section image should be located inside the section image frame.

**Screenshots**
Here is the section image is displayed correctly in LTR mode:
![Grid format - LTR mode](https://user-images.githubusercontent.com/51836675/226123035-531e0369-5a9c-4660-8782-3f7d03065eab.png)

And here is how it is displayed incorrectly in RTL Mode:
![Grid format - RTL mode](https://user-images.githubusercontent.com/51836675/226123072-e2b6c2b5-9cf6-42c1-9853-04e6ca2f3eb7.png)

Could you please fix this issue? For RTL users it makes the format unusable, and we like the format very much :-)

**Versions**
 - Moodle: 4.2.1
 - Format: 401.0.2 (2022112601)
 - Browser and version: Chrome v110.0.5481.177

Please note that although it is somehow realted to this issue:
https://github.com/gjb2048/moodle-format_grid/issues/175
It's not the same thing. The #175 issue deals with a missing feature, while here I report something that is considered a bug, in my  opinion.

It would be great if you could fix this issue, so we could continue to use this wonderful course format.
Thanks even just for reading all this bug report :-)

**Comment by gjb2048** [comment]
Same as #173 and will be released soon.

**Comment by gjb2048** [comment]
Moodle 4.2?

**Comment by acquaalta** [comment]
Hi Gareth,
It was supposed to be 4.1.2, but my mined flipped part of it to 2.1 :-) I now updated the text and fixed the bug of the Moodle version in my description :-)
