### ISSUE TITLE
PNG files in Grid fail when imported or uploaded. 

### ISSUE THREAD

**Issue by vlashdn** [gjb2048/moodle-format_grid#18]
Instead of getting the PNG file, it comes out Black. Using a GIF file works fine. Does not affect the rest of the course, just the GRID PNG files.

Moodle 2.9.1+ (Build: 20150806)
Grid format
format_grid
Additional	 2015062202	2.9.1.2

**Comment by gjb2048** [comment]
Is the GD library installed correctly?

**Comment by vlashdn** [comment]
The problem with Mac Yosemite's GD Library install. It does not include PNG support. Have to manually rebuild PHP. Thanks for the hint as to where to look.
