### ISSUE TITLE
[3.11] Restore or duplicate course cause reset number of sections

### ISSUE THREAD

**Issue by CartierPierre** [gjb2048/moodle-format_grid#182]
**Describe the bug**
When we duplicate or restore a course (using Moosh or from the interface), the number of sections is moving from X to 6 (in my case, 2 to 6).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to copy course

**Expected behaviour**
It should be the same value

**Versions (please complete the following information):**
 - Moodle: 3.11.13+
 - Format: 3.11.1.3 (build 2021102703)

**Additional context**
We found a hack to read in db the value of the initial course and updating the duplicated with the good value. Not clean.
I don't know if it's related to https://github.com/gjb2048/moodle-format_grid/issues/126

Thanks

**Comment by gjb2048** [comment]
Can't replicate on M4.2 version and that has identical code in this https://github.com/gjb2048/moodle-format_grid/blob/master/lib.php#L308-L316 respect that affects the value of 'numsections' in the new course.  To test on M3.11 would take time as I'd need to switch back to PHP 7.4 from 8.0.
