### ISSUE TITLE
Grid sometimes loads with blocks misaligned

### ISSUE THREAD

**Issue by thepurpleblob** [gjb2048/moodle-format_grid#22]
This is intermittent but reasonably easy to reproduce. Here is an example with the Clean theme...

![screen shot 2016-01-18 at 11 35 04](https://cloud.githubusercontent.com/assets/664139/12390491/62421870-bdd8-11e5-977a-c32e116ac7e1.png)

Here with the Bootstrap3 (optional) theme...

![screen shot 2016-01-18 at 11 41 47](https://cloud.githubusercontent.com/assets/664139/12390511/879fa614-bdd8-11e5-9806-32e2176e0bb2.png)

This seems to happen with any Grid format course. Just reloading the page a few times is enough for it to happen. Oddly, merely mousing over the block is usually enough to properly align it. 

It's more pronounced on a big monitor with the page view as wide as possible. I tested this on Moodle 2.9.3 and Grid format version 2015062205.

**Comment by gjb2048** [comment]
Thanks Howard.   Odd.  Very odd.  I'll look into it.

**Comment by gjb2048** [comment]
Any particular browser?  Is section 0 in the grid?

**Comment by thepurpleblob** [comment]
I'm on OSX (but the person who reported it to me was on Windows). I have tried it on Chrome, Safari and Firefox. Just the same. They tried it on IE. 

To be perfectly honest, I've never actually used Grid Format but I think section 0 is the first box.

**Comment by thepurpleblob** [comment]
TBH... now I look again, I'm wondering if the person building the course has done something mad. I'm struggling to think what though. The grid takes a surprisingly long time to load. Compared to attempts of my own anyway. The images all seem to be the right size (don't know if you scale them on upload).

**Comment by gjb2048** [comment]
The format does scale the images and serve its own correct size version.

**Comment by thepurpleblob** [comment]
On further investigation this might be somebody doing something crazy... unfortunately I can't figure out what it is. Any thoughts appreciated.

**Comment by gjb2048** [comment]
Thoughts: umm, ask them what they have done.

**Comment by thepurpleblob** [comment]
Yeh.... I tried that. If you don't have enough information to reproduce this (I didn't) and nothing jumps to mind then please feel free to close this as "cannot be reproduced". I won't be offended and I tried ;-)

**Comment by gjb2048** [comment]
Hi Howard,

If possible, could you backup the course and send me the mbz file to try?

Cheers,

Gareth

**Comment by thepurpleblob** [comment]
It'll be quite big. Can I PM you a download link of some sort? What's the best (private) contact for you?

**Comment by gjb2048** [comment]
Hi Howard,

I'll message you on Moodle.org.

Cheers,

Gareth

**Comment by gjb2048** [comment]
I have found some inline CSS:

    /* <![CDATA[ */
    .course-content ul.gridicons li p.icon_content {
        width: 258px;
    }
    .course-content ul.gridicons li .image_holder {
        width: 256px;
        height: 170.66666666667px;
        border-color: #025478;
        background-color: #f1f2f2;
        border-width: 1px;
        
    }

        .course-content ul.gridicons li:hover .image_holder {
        box-shadow: 0 0 0 1px rgba(2,84,120, 0.3);
    }

    .course-content ul.gridicons li.currenticon .image_holder {
        box-shadow: 0 0 2px 4px #8E66FF;
    }

    .course-content ul.gridicons li.currentselected {
        background-color: #96D7FC;
    }

    .course-content ul.gridicons img.new_activity {
        margin-top: 129.66666666667px;
        margin-left: 162px;
    }

    /* ]]> */

on the page.

**Comment by thepurpleblob** [comment]
I assume you mean not of your making?

Any thoughts why someone might add this?

**Comment by gjb2048** [comment]
Oh 'fudge' its my code.  So much time in Essential you forget the real world.  Meh!

**Comment by gjb2048** [comment]
Whata mistakea to makea!

**Comment by gjb2048** [comment]
This has got to do with the JS initialisation somewhere.

**Comment by gjb2048** [comment]
Hi Howard,

Can you make this harmless patch: https://github.com/gjb2048/moodle-format_grid/commit/2d59b21a51d0c1faaa2d1a11a31bc62e8b0a9c8e#diff-828043dc9f8d10ccd58ff8b96297794fL1296 and see if it fixes it for you please.

Cheers,

Gareth

**Comment by thepurpleblob** [comment]
Sorry... been away for a few days. Thanks for this, we'll have a look. Local politics make it difficult to patch the production server without lots of meetings and paperwork unfortunately. Will check on the test box though.

**Comment by gjb2048** [comment]
No worries Howard.
