### ISSUE TITLE
new activity picture for Arabic

### ISSUE THREAD

**Issue by hannaedelman** [gjb2048/moodle-format_grid#32]
Hi, we created a new_activity strip in Arabic, 
attached.
Hanna

![new_activity_ar](https://cloud.githubusercontent.com/assets/15798114/16989682/cce934f0-4e9d-11e6-8071-b8931869e575.png)

**Comment by gjb2048** [comment]
Hi Hanna,

Thank you, what is the specific language 639-1 code I need for the shown language (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) please?

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Hi Hanna,

Sorry, but I cannot integrate without my question being answered.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Closing as information not supplied.
