### ISSUE TITLE
When uploading animated gif as a section image, the it's not animated

### ISSUE THREAD

**Issue by leac** [gjb2048/moodle-format_grid#34]
Is t possible to have animated gif's as section images?  
When I upload the following gif, I get a static image
![bagel1](https://cloud.githubusercontent.com/assets/1826720/18343395/f0709518-75bb-11e6-9357-f1a8bb70ae89.gif)

**Comment by nadavkav** [comment]
+1
(I think/guess php-gd is converting the uploaded gif image to a single frame gif image)

**Comment by gjb2048** [comment]
As Nadav says, cannot do due to GD lib.

**Comment by nadavkav** [comment]
Maybe possible if... we add a checkbox "Do not mess with my animated gif, I uploaded it exactly as you told me (width=WW & height=HH)" ?

Detect animated gif with GD:
http://stackoverflow.com/questions/280658/can-i-detect-animated-gifs-using-php-and-gd

Resize animated GIF file without destroying animation
http://stackoverflow.com/questions/718491/resize-animated-gif-file-without-destroying-animation?noredirect=1&lq=1
