### ISSUE TITLE
Grid Alignment for Missing Images

### ISSUE THREAD

**Issue by roperto** [gjb2048/moodle-format_grid#35]
Hi, I think this is may not be an issue (it could be an enhancement though), but we could add an option to properly align all sections even when there is a missing image.

Example:
![selection_001](https://cloud.githubusercontent.com/assets/3672494/19672895/4c91eb4c-9ac6-11e6-867a-fe3b163b3253.png)

We achieved that by 'mimicking' an empty image when it was blank.

Example:
![selection_003](https://cloud.githubusercontent.com/assets/3672494/19674843/81b2beea-9ad6-11e6-984a-1a479bf2afe3.png)

Cheers,
Daniel

**Comment by gjb2048** [comment]
But.... the code already copes with this situation by having an empty box.  Why do I need to 'enhance' something that is not even broken in the released code as it stands?

**Comment by roperto** [comment]
Hi Gareth,

I am installing from the master branch in Moodle 3.1. If I provide pictures for only a few sections, I get the view like in the first image, while I wanted to see something like the second image.

Was it supposed to be always like in the second image?

Cheers,

Daniel

**Comment by roperto** [comment]
Hi Gareth,

My apologies, it seems like the plugin works fine without images and my theme was breaking it.

Cheers,

Daniel
