### ISSUE TITLE
Section title rendering broken if no title provided

### ISSUE THREAD

**Issue by roperto** [gjb2048/moodle-format_grid#36]
If a section has no title (a space as title for example) it does not render properly. Please see attachment.

![selection_001](https://cloud.githubusercontent.com/assets/3672494/19749125/35a90a38-9c32-11e6-8417-5589f3bd691c.png)

**Comment by gjb2048** [comment]
Ok, what version of Moodle and the Grid format are you using?  What changes have you made to the format?

**Comment by roperto** [comment]
Hi.

I am using the master branch with Moodle 3.1 -- to fix that, I did a dirt workaround replacing the title to &nbsp; if it was blank after trimming.

I can make a pull request, but maybe you have a better solution than mine.

Cheers,
Daniel

**Comment by roperto** [comment]
Hi,

I updated the image in my comment above to reflect how it looks like with the default there, I hope it helps.

To reproduce, just change a title to contain only a space character.

Cheers,

Daniel
