### ISSUE TITLE
Embedded videos still load in one section per page mode.

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-format_grid#39]
From Ken: https://moodle.org/user/profile.php?id=2028626

We are using it with "Show one section per page". Our problem is that each section has multiple embedded videos and this is resulting in a very slow load of the main page. From what I can see the main page source includes all the content of the various sections even though they are not displayed when showing one section per page. Is this correct? Is there any way to avoid this?
...
I have done a test on an empty course and found the following
• I am using Moodle 3.0.5 (Build: 20160711) with the BCU theme
• I set up the course in topics format with one page per topic. In the first topic I added a label with an embedded youtube video. 
• The page source for the main page does not contain any reference to that video which is what we would want. 
• If you turn on edit mode the main page does contain the youtube video, indeed it displays it as it shows all the topics on one page to make editing easier.
• If I then change the course format to Grid format with edit mode off the page source for the main page does include the youtube embed data, even though it is not displayed on the page. Obviously if I turn on edit mode the video is actually displayed.

What I think is happening is that instead of not loading the data from each section when not in edit mode, you are loading it but not displaying it. This would not be a problem except that we are using the course to store numerous embedded videos (50+), so load times become a really issue. We would be happy to do a temporary hack of the code to get this working on our site, but are reluctant to do that if any future updates will need a similar hack. 

In case it helps, below is the bit of code copied from the page source that includes the youtube link, sorry about the poor formating of this.

**Comment by KenFarr** [comment]
Just to confirm, I have also tried this with identical result on a site running Moodle 2.8.7 using the Essential theme.
Ken

**Comment by gjb2048** [comment]
Ok, can reproduce.
