### ISSUE TITLE
Managers assigned at Course Category levels cannot create a course with grid format selected

### ISSUE THREAD

**Issue by thepurpleblob** [gjb2048/moodle-format_grid#42]
Somebody with the Manager role (at category level) tries to create a new course and selects the Grid course format. The page simply refreshes and does not save. No errors are shown. 

This sounds very similar to this.. https://github.com/gjb2048/moodle-format_topcoll/issues/24

**Comment by gjb2048** [comment]
Hi Howard,

Ok, what version of Moodle and the format are you running please?  Are there any errors in the php.log file?

G

**Comment by thepurpleblob** [comment]
Hi Gareth,

It's Moodle 3.1.3 and Grid 2016060702. There's nothing logged for this issue.

**Comment by gjb2048** [comment]
Hi Howard,

I can reproduce, will look and see if the same fix as CT.

G

**Comment by gjb2048** [comment]
It is interesting that /course/format/lib.php uses the pre-fixed CT solution, so therefore do core formats have this issue too?

**Comment by gjb2048** [comment]
Fix is the same as https://github.com/gjb2048/moodle-format_topcoll/issues/24 - will start in M3.2 then back-port.

**Comment by gjb2048** [comment]
Re-open to backport.
