### ISSUE TITLE
Missing closing DIV

### ISSUE THREAD

**Issue by dmitriim** [gjb2048/moodle-format_grid#43]
On branch MOODLE_31 (haven't tested on others)

If you use "Show one section per page" settings then there is missing closing DIV which breaks page layout.
 
![image](https://cloud.githubusercontent.com/assets/4626431/23048511/6bb4e68e-f50a-11e6-80ae-359d3f44bccc.png)

^^ "aside" sections should be outside of "region-main" container.

**Comment by gjb2048** [comment]
Thanks Dmitrii, I can replicate, G.
