### ISSUE TITLE
v2.9.1.8 broken in IE8 

### ISSUE THREAD

**Issue by jamestombs** [gjb2048/moodle-format_grid#47]
I know it's an old IE version but we found a simple one line fix so thought we'd share back.

In IE8 only the first and last grid elements open up in the modal, all other grid elements produce the following error when clicked:

> Can't move the focus to the control because it is invisible, not enabled, or of a type that does not accept the focus.

If you open modal with first or last and use arrows to navigate the other sections just appear blank.

Issue is on line 252:

`firstactivity.focus();`

The .focus() is being called before IE has time to render the content so if a small timeout is added before the focus it fixes it.

`setTimeout(function() { firstactivity.focus(); }, 10);`

**Comment by gjb2048** [comment]
Hi James,

Ok, thanks for the information.  Umm, line 252 of what please?

Gareth

**Comment by jamestombs** [comment]
That would certainly help wouldn't it. 

module.js and it actually looks like line 243 with the latest code on here which I assume will have the same issue.

**Comment by gjb2048** [comment]
Hi James,

Ok ta, but.... looking at the M2.9 release notes: https://docs.moodle.org/dev/Moodle_2.9_release_notes#Browser_support - IE9 is the minimum version.  Therefore I don't want to put in code to support old browsers when that just adds more stuff that is not really needed.  More stuff = more to go wrong = less efficient code.

G

**Comment by jamestombs** [comment]
Fair enough, at least the fix is available incase anyone else has the misfortune to have to support IE8.,

**Comment by gjb2048** [comment]
Or IE (any version) for that matter ;)
