### ISSUE TITLE
Allow students to click through units

### ISSUE THREAD

**Issue by jdiez17** [gjb2048/moodle-format_grid#5]
It'd be great to have the option to open a new tab upon clicking a unit link in the format_grid plugin. Perhaps it'd be good to add a configurable option. 

If you don't have time to work on this I'd be happy to help implement it myself, but I'd need some guidance.

Thanks a lot.

**Comment by gjb2048** [comment]
@jdiez17 Still an issue?

**Comment by gjb2048** [comment]
@jdiez17 Closing as no reply after eight years!
