### ISSUE TITLE
gridcontainer alignment

### ISSUE THREAD

**Issue by mnods** [gjb2048/moodle-format_grid#54]
moving from 3.1.x to V3.2.1.3 - noticed grid container not aligning per format setting. the "Set the image container alignment" sets #gridcontainer div to text align of left right or centre but it doesn't appear to make any difference - think it needs a width and or a float, but can't get it to sit right at my end. the setting should probably say it's the outer container setting perhaps? - the settings below that refer to the grid boxes. unless i'm totally confused... which is v possible :) 
using latest 3.2 essential but same in clean.

**Comment by gjb2048** [comment]
Down to change to using 'flexbox'.

**Comment by gjb2048** [comment]
M3.2+ only ATM.  Will be M3.1 if https://github.com/gjb2048/moodle-format_grid/commit/82da686010bb53dab22c697862ce2440d92a80e3#diff-4e7bb40584b55a44f4657b188986bff4R95 back-ported.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-format_grid/commit/625f52a9409bed5431f99c20dad7e4c566d7abc3
