### ISSUE TITLE
Support stealth activities

### ISSUE THREAD

**Issue by thepurpleblob** [gjb2048/moodle-format_grid#56]
It would be great if this format supported the new stealth feature introduced in 3.3

**Comment by gjb2048** [comment]
Hi Howard,

V3.3.0.1 does: https://moodle.org/plugins/pluginversion.php?id=14456.

G

**Comment by thepurpleblob** [comment]
That's odd.... how come I running version 3.2.1.2 and it claims to be the most recent version?

**Comment by gjb2048** [comment]
V3.3.0.1 is beta?

**Comment by gjb2048** [comment]
You are on M3.3?

**Comment by thepurpleblob** [comment]
Yeh - I have (Grid 3.2.1.2) installed in a 3.3.1 Moodle and there is definitely a 3.3 in the plugins versions. Is it that having the "wrong" branch somehow breaks the new version check? That would be a bit of a bug I suppose. 

I installed Grid 3.2.something before there was a 3.3 version

**Comment by gjb2048** [comment]
I don't know: https://github.com/gjb2048/moodle-format_grid/blob/master/version.php#L36-L42

**Comment by thepurpleblob** [comment]
It wouldn't be a big deal but I have to jump through hoops and do mountains of paperwork to update stuff on the live servers. 

Oh well :)
