### ISSUE TITLE
No visual feedback of hidden sections

### ISSUE THREAD

**Issue by thepurpleblob** [gjb2048/moodle-format_grid#58]
The 'box' for a hidden section is not displayed at all for students. However, for staff, there is no visual feedback at all that the block is hidden. This sometimes leads to mistakes with them not realising it has been hidden.

It would be very useful if it could be styled differently or a 'hidden from students' label floated over the image to make this clear.

**Comment by gjb2048** [comment]
Hi Howard,

What version of the format / Moodle and what are the steps I need to take to replicate please?

Gareth

**Comment by gjb2048** [comment]
Note to self:

            if (!$showsection) {
                // If the hiddensections option is set to 'show hidden sections in collapsed
                // form', then display the hidden section message - UNLESS the section is
                // hidden by the availability system, which is set to hide the reason.
                if (!$course->hiddensections && $thissection->available) {
                    echo $this->section_hidden($section, $course->id);
                }

                continue;
            }

....

            $showsection = $hascapvishidsect || $sectionvisible;

            // If we should grey it out, flag that here.
            $sectiongreyedout = false;
            if ((!$showsection) && ($this->settings['greyouthidden'] == 2)) {
                $sectiongreyedout = !$thissection->uservisible;
            }
