### ISSUE TITLE
Open activities in a popup window

### ISSUE THREAD

**Issue by actXc** [gjb2048/moodle-format_grid#6]
The grid format makes navigation for unexperienced users much easier to understand.
But if a section has activities like forum, feedback, qiz etc. they open flat and the user gets lost, because it not very logic how to go back to where they came from. 
It would be logic, if the activity opens in the popup window and offers a similar close button like the section.
I think there could be a chance to find a way to offer such additional popups.
So much similar code is already there.

**Comment by gjb2048** [comment]
@actXc Still an issue?

**Comment by gjb2048** [comment]
No reply, closing.
