### ISSUE TITLE
Grid with essential fixed nav - nav bar overlaps the grid section when opened

### ISSUE THREAD

**Issue by mnods** [gjb2048/moodle-format_grid#64]
tested in 

grid 3.2.1.3
essential V3.2.1.3

same thing appears in:

grid V3.3.0.2
V3.3.1.1 essential
https://static.murdoch.edu.au/lms/img/grid-essential-navbar.png

**Comment by gjb2048** [comment]
![grid-essential-navbar](https://user-images.githubusercontent.com/1058419/32740811-0dc00886-c89c-11e7-8be4-8ac89a2937d1.png)

**Comment by gjb2048** [comment]
Thanks Mike.

**Comment by gjb2048** [comment]
Notes:

https://github.com/gjb2048/moodle-format_grid/commit/216e830f9aa04368451f866cccbc88131c0ffa01

https://github.com/gjb2048/moodle-theme_essential/commit/1a45a42bb21c4a30b8ccb08d3e57a4c69dac5aa7#diff-f028cb2441d5353c7fce2b508e76bce8R17

**Comment by gjb2048** [comment]
So timeline disparity.

**Comment by gjb2048** [comment]
Fixed I think.
