### ISSUE TITLE
Stealth activities

### ISSUE THREAD

**Issue by cb526** [gjb2048/moodle-format_grid#69]
Hi Gareth,

Someone reported this in the Moodle forums, and I was able to reproduce it. The option to use Stealth Activities is unavailable with the Grid format for any new activities.
Please see screenshot. You'll see one activity (Announcements) that was there already and set to stealth mode. I changed the course format to grid format, and I added another item (Label). The option to make available/unavailable is not visible on the course page or in 'Common Module Settings' in the label settings.

![image](https://user-images.githubusercontent.com/15820803/37282303-d8d1efd8-25eb-11e8-8fc2-36e165971eae.png)

If I change back to topics format, the option to change to stealth mode still does not appear for this label. However, if I add new activities again I can enable stealth mode.
Interestingly, I am am now unable to duplicate the labels (undefined error). I don't if it's related or not but including it just in case.

**Comment by gjb2048** [comment]
Ok....

What version of the Grid format?
What version of Moodle?
Did you know that Stealth Activities was dropped in M3.4?

**Comment by cb526** [comment]
No I didn't! Sorry about that. Maybe that negates this issue then. Though the Moodle site I have here for testing 3.4 did come with Stealth option available in Advanced Features.

Moodle version is Moodle 3.4.1+ (Build: 20180223) Version 2017111301.06]
Grid format is 3.4.0.2 - 2017111801

Thanks

**Comment by cb526** [comment]
Could it be that you mean orphaned activities are no longer allowed (rather than https://docs.moodle.org/34/en/Stealth_activities) ?

**Comment by gjb2048** [comment]
Ops, yes, I did mean orphaned activities.

**Comment by gjb2048** [comment]
I'll look into it.

**Comment by cb526** [comment]
Thank you!

**Comment by gjb2048** [comment]
Cannot reproduce, see linked forum post.
