### ISSUE TITLE
Implement Moodle's Privacy API to comply with GDPR

### ISSUE THREAD

**Issue by ewallah** [gjb2048/moodle-format_grid#70]

**Comment by gjb2048** [comment]
Ok... is this a request, an instruction, telling me what to do or what exactly please?

**Comment by ewallah** [comment]
Sorry about not being clear, but if you want that European or International sites keep using the grid format after May 25,  you will have to implement a privacy provider interface:

- https://docs.moodle.org/34/en/GDPR_FAQ
- https://docs.moodle.org/dev/Privacy_API

So, indeed this is a request to add all privacy related code, as most European admins are now writing policy after policy after policy.

**Comment by gjb2048** [comment]
Ok.... I did know about this, hence my comments on:

https://moodle.org/mod/forum/discuss.php?d=365857
https://moodle.org/mod/forum/discuss.php?d=352538

And my work / articles on Collapsed Topics with GDPR.

But strictly speaking what you're saying is false as "Sorry about not being clear, but if you want that European or International sites keep using the grid format after May 25" as it is more specifically pertaining to sites that contain EU member citizens data.  Therefore only applies internationally if that site has user who resides within the European Union.

**Comment by gjb2048** [comment]
In any event, the plugin is free and open source, so may or may not be ready by then.

**Comment by gjb2048** [comment]
Oh and my post here: https://moodle.org/mod/forum/discuss.php?d=364186.

**Comment by thepurpleblob** [comment]
+1
Pretty please. It would be great to have this. 

I may be along with a pull request but I have a big list of them :-D

**Comment by gjb2048** [comment]
Hi Howard,

I suspect that the Grid format will implement 'null provider' as does not actually store any user specific data.  But need to check.

Umm... pull requests scare me as I have the format as intended.  What do you have in mind and why?

Gareth

**Comment by thepurpleblob** [comment]
If it is a null provider  - and I suspect it is - it's a five minute job. I think you can reasonably expect to get nagged about this as 3.5 is rolled out. 

Doing a proper implementation of the API for plugins that do store personal data is a big PITA, unfortunately.

**Comment by gjb2048** [comment]
Hi Howard,

Ok, the think is that it might be a five minute job to implement (and I have done this before), however 'I' still need to be sure that there is no personal data - thus including pull requests.

I must point out that I have a tendency for 'nagging' to only make me stick my feet into the ground more and NOT do something.  It tends to really 'really' annoy me as I'm doing this on my own time.  Hint hint.  Thus I will get around to this at some point but on my terms.

Gareth

**Comment by thepurpleblob** [comment]
Just offering help if you wanted it. If I've caused some sort of offence then I'm sorry. 

Fully understand it's all on your own time and good will.

**Comment by gjb2048** [comment]
Thanks foe the offer of help Howard.

**Comment by gjb2048** [comment]
Done.
