### ISSUE TITLE
Section title box position option 'outside' no longer works

### ISSUE THREAD

**Issue by uoliaso** [gjb2048/moodle-format_grid#73]
Using format_grid 3.4.0.4 (2017111803) on Moodle 3.4.2 (Build: 20180319):

When I set the 'Section title box position option' to 'outside' I'm expecting to see the section title outside of the box. It seems to stay inside the box. Switching back and forth between 'inside' and 'outside' produces no change.

My expectation is that the option 'inside' places the title at 'A' in the image below and that the 'outside' places it at position 'B'. Apologies for messy image.

![image](https://user-images.githubusercontent.com/23505672/42156817-00a74530-7de4-11e8-873a-d7691b15f685.png)

I've checked on an instance of Moodle 3.2.2 (Build: 20170313) using format_grid 3.2.1.3 (2016111505) and the 'outside' option works correctly, as shown below.

![image](https://user-images.githubusercontent.com/23505672/42157095-b4c1b56e-7de4-11e8-80e4-a35a04ac2920.png)

Is this a bug or is there some combination of other settings I am missing?
many thanks

**Comment by gjb2048** [comment]
What theme are you using?

**Comment by uoliaso** [comment]
I'm using an in-house theme. Taking the hint from your question I've tested using Boost and Clean and they both work correctly. Apologies for not checking with a standard theme before reporting! 

I've found a grid format related scss file in this theme which when I disable it gives me expected behaviour. I'll have to go report a bug in the theme - thanks for the pointer! You can mark this as badly-filed-bug now 😳

**Comment by gjb2048** [comment]
No problem, I'd rather know than not.
