### ISSUE TITLE
Horizontal grid in full screen

### ISSUE THREAD

**Issue by shankarj67** [gjb2048/moodle-format_grid#76]
Hi, 

Thank you for creating this plugin.

Is there any way to have one layout per line which is one course per line, for example, see the screenshot below

![screenshot 385](https://user-images.githubusercontent.com/11690680/46794530-a8ab7500-cd65-11e8-8fe6-ce63c643b754.png)

I wanted to have the layout like the above screenshot where one line will have one course, is there any chance I can do it using Grid plugin.

Regards,
Shankar Jha

**Comment by gjb2048** [comment]
Dear Shankar,

No because it is a course format.

Gareth
