### ISSUE TITLE
codingerror occured using the grid courseformat with moodle 3.5.x and the boost theme

### ISSUE THREAD

**Issue by moodlebeuth** [gjb2048/moodle-format_grid#79]
Hello,

we are using moodle 3.5.2 and the latest version of your course format grid plugin (release = '3.5.0.2'). Before the upgrade of the moodle system coming from version 3.3.x the old moodle course with a clean theme worked fine. But now the course is using the new boost theme and the following error occured:

> [Wed Nov 07 17:08:37.321091 2018] [:error] [pid 29119] [client x.y.z.a:43810] Default exception handler: Coding error detected, it must be fixed by a programmer: The theme has already been set up for this page ready for output. Therefore, you can no longer change the theme, or anything that might affect what the current theme is, for example, the course. Debug: Stack trace when the theme was set up: <ul style="text-align: left" data-rel="backtrace"><li>line 677 of /lib/pagelib.php: call to moodle_page->initialise_theme_and_output()</li><li>line 820 of /lib/pagelib.php: call to moodle_page->magic_get_theme()</li><li>line 80 of /course/format/grid/lib.php: call to moodle_page->__get()</li><li>line 190 of /course/format/lib.php: call to format_grid->__construct()</li><li>line 35 of /course/format/lib.php: call to format_base::instance()</li><li>line 2684 of /lib/modinfolib.php: call to course_get_format()</li><li>line 545 of /lib/modinfolib.php: call to section_info->__construct()</li><li>line 418 of /lib/modinfolib.php: call to course_modinfo->__construct()</li><li>line 2169 of /lib/modinfolib.php: call to course_modinfo::instance()</li><li>line 2559 of /lib/moodlelib.php: call to get_fast_modinfo()</li><li>line 3002 of /lib/moodlelib.php: call to require_login()</li><li>line 65 of /mod/forum/view.php: call to require_course_login()</li></ul>\nError code: codingerror\n* line 1918 of /lib/pagelib.php: coding_exception thrown\n* line 1001 of /lib/pagelib.php: call to moodle_page->ensure_theme_not_set()\n* line 1084 of /lib/pagelib.php: call to moodle_page->set_course()\n* line 2693 of /lib/moodlelib.php: call to moodle_page->set_cm()\n* line 3002 of /lib/moodlelib.php: call to require_login()\n* line 65 of /mod/forum/view.php: call to require_course_login()\n, referer: https://moodle.server.com/course/view.php?id=12345

Do you have any idea, what the problem is here?

Thanks & Greetings,
Michael

**Comment by gjb2048** [comment]
Please use an official released version, i.e. from https://moodle.org/plugins/pluginversions.php?plugin=format_grid.  The master branch on GitHub is development.

**Comment by moodlebeuth** [comment]
I used the official version before with the same result.

**Comment by gjb2048** [comment]
Ok, fair enough, I'll need to fix it when I can.

**Comment by gjb2048** [comment]
Not seen this issue with past versions of M3.5.

**Comment by gjb2048** [comment]
Or stick to tagged versions here: https://github.com/gjb2048/moodle-format_grid/releases.

**Comment by moodlebeuth** [comment]
Yes, you were right. With the downgraded version it works as expected.

Thanks & Greeting,
Michael
