### ISSUE TITLE
"Section 0 on its own page when out of the grid and on a single section page" doesnt seem to work

### ISSUE THREAD

**Issue by Jarvil** [gjb2048/moodle-format_grid#83]
Hello,

I have set in the course settings:

- Course layout: **show one section per page**
- Section 0 on its own page when out of the grid and on a single section page: **No**

But nothing changes on a course. Section 0 isn't displayed as a grid section it just stays as a different page all the time. Tried with Boost-theme, format_Grid 3.5.0.3 (2018052302) & Moodle 3.5.

**Comment by Jarvil** [comment]
Hello,

What is the purpose of setting "Section 0 on its own page when out of the grid and on a single section page" when nothing changes on the course? See attached video.

[grid_setting.zip](https://github.com/gjb2048/moodle-format_grid/files/2720641/grid_setting.zip)

**Comment by gjb2048** [comment]
If you look at any of the single section pages for any section you'll find that section 0 is no longer at the top but rather on its own page and accessible via both the navigation and jump to menu!

**Comment by Jarvil** [comment]
Hello,

Ok thanks, now I understand the meaning.
