### ISSUE TITLE
Issue viewing a course section when specifying sectionid as param

### ISSUE THREAD

**Issue by 5882wolverine** [gjb2048/moodle-format_grid#84]
Hi,

If you try to go to a section using "sectionid" (as opposed to the usual section param) in the querystring param, i.e. the actual dB id, it doesn't display the section content.  So for example, say a course of id 20, has a section id in the dB of 100 (and is section number 4), this would work:

course/view.php?id=20&section=4

However, this wouldn't work:
course/view.php?id=20&sectionid=100

Testing this with the standard weekly format, this works as expected.  Also this was tested on latest grid format version on Moodle 3.6.2

**Comment by gjb2048** [comment]
Implemented in https://github.com/gjb2048/moodle-format_grid/commit/669a1118544292c9a9c1d1a16bb77e5a101b83d7.
