### ISSUE TITLE
Hover effect suggestion

### ISSUE THREAD

**Issue by cb526** [gjb2048/moodle-format_grid#85]
Hi there,

Thanks again for this great course format. 
I found the images in the grid getting a little fuzzy on hover. I have addressed this by changing the scale from 
```
.course-content ul.gridicons li img:hover {
    transform: scale(1.2);
```

to 

```
.course-content ul.gridicons li img:hover {
    transform: scale(0.9);
```
in my custom CSS.

Just sharing if it's of interest.
Thanks

**Comment by gjb2048** [comment]
Thanks but that CSS isn't in the format!
