### ISSUE TITLE
Images lost after upgrade

### ISSUE THREAD

**Issue by callumlew** [gjb2048/moodle-format_grid#86]
After upgrading moodle from 3.1 > 3.5 and upgrading the plugin, images have been lost which form part of the grid format view.

Is there any way to retrieve these images?

Thansk

**Comment by gjb2048** [comment]
The format should be fine with upgrades.  Could have been caused by upgrade procedure / process.

You can get the images back from the backups (course or otherwise) that you made before the upgrade.

**Comment by gjb2048** [comment]
Any progress on this please or can I close it?  If no response within a reasonable time then I'll close it anyway.

**Comment by gjb2048** [comment]
Ok, giving up on this.  Offered support, no reply!  Don't want to waist any more of my time.  If you're going to raise an issue at least have the courtesy to follow it though.
