### ISSUE TITLE
dbconnectionfailed

### ISSUE THREAD

**Issue by mgardener** [gjb2048/moodle-format_grid#87]
Hi, It gives and db error while rendering grid images. There is no specific error log.  Moodle version is 3.3.

![2019-03-07_1028](https://user-images.githubusercontent.com/3392373/53967969-347ebe80-40c4-11e9-8271-76a9cb97f886.png)

**Comment by gjb2048** [comment]
Ok, from the information provided = I don't know!

Have you looked to see if there is a stack trace because of white text on a white background?

Have you looked in the PHP error log?

**Comment by mgardener** [comment]
There is no white text and any PHP error log.

**Comment by gjb2048** [comment]
Fair enough.  Please turn on developer level debugging.  There is an PHP log, look in the php.ini file.

**Comment by gjb2048** [comment]
Can I close this please Micheal?

**Comment by mgardener** [comment]
Yes. It was a weird server problem. I switched the server that site is hosted in. Thank you.
