### ISSUE TITLE
Number of sections decreased after upgrading to latest version

### ISSUE THREAD

**Issue by anieminen** [gjb2048/moodle-format_grid#90]
Hello,

Yesterday we upgraded Grid format from 3.5.0.4 to the latest version 3.5.0.5 in Moodle 3.5.5. Moodle core was not upgraded at this point.

After the upgrade it seems that every Grid format course has the default number of sections (2). On some courses there were a lot more sections before the upgrade with activities in them. Of course the number of sections can be changed from course settings in the latest version. But teachers are quite confused about all the orphaned activities on their courses.

Is this a bug?

**Comment by gjb2048** [comment]
I don't know as did not happen in tests.  Did you test on a test server first?

**Comment by anieminen** [comment]
Tested on a test server too, but didn't notice the problem there before the production server upgrade. The same thing happened on two Moodle 3.5.5 instances on different servers.

**Comment by gjb2048** [comment]
Ok, I've disabled the release on Moodle.org for now until I can investigate.  I suggest that you don't install anywhere else at all.  Please keep hold of any backups to the DB before the upgrade.

**Comment by gjb2048** [comment]
Related https://tracker.moodle.org/browse/CONTRIB-7393

**Comment by gjb2048** [comment]
Ok, I can replicate.  So, on your production servers whatever you do, do NOT go to the course settings of the affected courses and change / save the settings.

**Comment by gjb2048** [comment]
I will have a fix soon, but for it to work then you must not have a 'numsections' entry for each affected course in the 'course_format_options' table, unless with a given course you have orphaned activities / resources that you wish to has as is.

**Comment by gjb2048** [comment]
Fixed.  Please see: https://moodle.org/mod/forum/discuss.php?d=384851#p1552047.

**Comment by anieminen** [comment]
Thanks!
