### ISSUE TITLE
Fixed line height in Boost

### ISSUE THREAD

**Issue by sharpchi** [gjb2048/moodle-format_grid#95]
I'm using M3.6 with v2018121906 of Grid format (3.6.0.6) with a Boost derived theme.
The line height of #gridmiddle-column is hardcoded to 1 and was wondering if that was necessary. In my theme and boost au naturel the text gets scrunched up - see screenshots of with and without line-height: 1.

I can override the line height in my theme, but thought it might affect others too.
thanks

![gridformat-space](https://user-images.githubusercontent.com/3774280/60973211-b7887d80-a31f-11e9-9f36-c1b349f9f094.png)

**Comment by gjb2048** [comment]
Hi Mark,

Would have been done for a reason for M3.2 - https://github.com/gjb2048/moodle-format_grid/commit/30a4dd0a358e1ee0c0a9320afeeca13a5e9c72b6 - I can't remember why though.  If it looks fine without it then can be removed but need to check that nothing is affected.

G

**Comment by gjb2048** [comment]
I don't really want to spend time checking if it will break anything so will leave as is until its clear its removal would not break anything.

**Comment by gjb2048** [comment]
No reply in ages, closing.
