### ISSUE TITLE
3.7.0.2 is marked at 'Beta'

### ISSUE THREAD

**Issue by universityofglasgow** [gjb2048/moodle-format_grid#99]
The version for Moodle 3.7 is marked at Beta code. That means that the 'available updates' check in Moodle completely ignores it (with standard settings). 

I'm not sure if this is intentional or an oversight. 

I picked this up because I seem to have the most recent non-beta version 3.6.something which has a number of fixed bugs in it.

**Comment by gjb2048** [comment]
Intentional beta because the code is beta.  When I get the impression its stable then I'll update it to stable.

**Comment by thepurpleblob** [comment]
Ok - but your "stable" version has the nasty vanishing images bug and your beta version doesn't. If you install the most recent stable version you are guaranteed to get that bug. 

Ask me how I know? Just sayin'
